fields:
  - name: timestamp
    period: -24h
  - name: client_response_code
    enum: [0, 1, 2, 3, 4, 5]
  - name: cluster_id
    cardinality: 100
  - name: colo_code
    enum: [SFO, JFK, LAX, LHR, FRA, NRT, SIN, SYD, GRU, MRS]
  - name: edns_subnet
    cardinality: 5000
  - name: edns_subnet_length
    range:
      min: 0
      max: 32
  - name: query_do
    enum: ["true", "false"]
  - name: query_name
    cardinality: 50000
  - name: query_rd
    enum: ["true", "false"]
  - name: query_size
    range:
      min: 20
      max: 512
  - name: query_tcp
    enum: ["true", "false"]
  - name: query_type
    enum: [1, 2, 5, 6, 12, 15, 16, 28, 33]
  - name: response_cached
    enum: ["true", "false"]
  - name: response_cached_stale
    enum: ["true", "false"]
  - name: source_ip
    cardinality: 10000
  - name: upstream_ip
    cardinality: 1000
  - name: upstream_response_code
    enum: [0, 1, 2, 3, 4, 5]
  - name: upstream_response_time_ms
    range:
      min: 1
      max: 500
