version: '2.3'
services:
  crowdstrike-logfile:
    image: alpine
    volumes:
      - ./sample_logs:/sample_logs:ro
      - ${SERVICE_LOGS_DIR}:/var/log
    command: /bin/sh -c "cp /sample_logs/* /var/log/"
  crowdstrike-streaming:
    image: golang:1.23-alpine
    hostname: crowdstrike
    working_dir: /app
    volumes:
      - ./sample_logs:/sample_logs:ro
      - ./streaming-mock-service:/app
    ports:
      - "8090:8090"
    environment:
      PORT: '8090'
    command: ["go", "run", "main.go", "--client_id", "xxxx", "--client_secret", "xxxx", "--access_token", "abcd", "--session_token", "xyz", "--file", "/sample_logs/falcon-event-stream.log", "--mock_datafeed_url", "http://svc-crowdstrike-streaming:8090/events"]
