rules:
  - path: /api/v2/gateways
    methods: ['GET']
    request_headers:
      Accept: application/json
      api-key: xxxx
      api-secret: xxxx
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {{ minify_json `
          {
            "gateways": [
              {
                "name": "Gateway_1",
                "default": false,
                "dns_server": "1.128.0.0",
                "email_when_connected": false,
                "email_when_disconnected": false,
                "email_recipients": [
                  "john.doe@example.com"
                ],
                "backup_ids": [
                  "backup1",
                  "backup2"
                ],
                "tunnel_proxy_settings": {
                  "enabled": false,
                  "tunnel_proxy_addr": "addr",
                  "tunnel_proxy_port": 8080,
                  "tunnel_proxy_user": "tunnel-proxy-01"
                },
                "id": "tunnel3",
                "status": "pending"
              },
              {
                "name": "Gateway_3",
                "default": false,
                "dns_server": "216.160.83.56",
                "email_when_connected": false,
                "email_when_disconnected": false,
                "email_recipients": [
                  "alias.doe@example.com"
                ],
                "backup_ids": [
                  "backup1",
                  "backup2"
                ],
                "tunnel_proxy_settings": {
                  "enabled": false,
                  "tunnel_proxy_addr": "addr1",
                  "tunnel_proxy_port": 8081,
                  "tunnel_proxy_user": "tunnel-proxy-02"
                },
                "id": "tunnel2",
                "status": "error"
              }
            ]
          }
          `}}
