version: '2.3'
services:
  microsoft_sqlserver:
    user: root
    build:
      context: .
      args:
        MSSQL_VERSION: ${MSSQL_VERSION:-2025-latest}
    ports:
      - 1433
    volumes:
      - ${SERVICE_LOGS_DIR}:/var/opt/mssql/log
