// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

package changelog

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/cli/go-gh/v2"

	"github.com/elastic/integrations/dev/gitutil"
)

// SyncResult holds outputs produced by CreateSyncPR.
type SyncResult struct {
	// NotFoundPackages lists package names that could not be resolved on main.
	NotFoundPackages []string
	// Outcome is "success", "skipped", or "error".
	Outcome string
}

// CreateSyncPR applies the changelog entries from entriesTSV onto main,
// commits them to workingBranch, and opens a GitHub PR.
// workDir is the repository root; an empty string uses the current working directory.
func CreateSyncPR(workDir, entriesTSV, workingBranch, backportPRNumber, backportBranch, packagesDir, repository string) (*SyncResult, error) {
	git := gitutil.Git{Dir: workDir}

	if !filepath.IsAbs(packagesDir) {
		packagesDir = filepath.Join(workDir, packagesDir)
	}

	if err := git.Run("checkout", "-b", workingBranch, "origin/main"); err != nil {
		return nil, fmt.Errorf("creating working branch: %w", err)
	}

	entries, err := readEntriesTSV(entriesTSV)
	if err != nil {
		return nil, fmt.Errorf("reading entries TSV: %w", err)
	}

	pkgIndex, err := BuildPackageIndex(packagesDir)
	if err != nil {
		return nil, fmt.Errorf("building package index: %w", err)
	}

	var notFound []string
	var applied []tsvEntry

	for _, e := range entries {
		pkgDir, ok := pkgIndex[e.pkg]
		if !ok {
			notFound = append(notFound, e.pkg)
			continue
		}

		changelogPath := filepath.Join(pkgDir, "changelog.yml")
		entryBlock, err := os.ReadFile(e.entryFile)
		if err != nil {
			return nil, fmt.Errorf("reading entry file %s: %w", e.entryFile, err)
		}
		_ = os.Remove(e.entryFile)
		if err := InsertEntry(changelogPath, e.version, strings.TrimRight(string(entryBlock), "\n")); err != nil {
			return nil, fmt.Errorf("inserting entry for %s: %w", e.pkg, err)
		}
		if err := git.Run("add", changelogPath); err != nil {
			return nil, err
		}
		applied = append(applied, e)
	}

	if len(applied) == 0 {
		_ = git.Run("checkout", backportBranch)
		return &SyncResult{NotFoundPackages: notFound, Outcome: "skipped"}, nil
	}

	commitMsg := buildCommitMessage(applied, backportPRNumber)
	prTitle := buildPRTitle(applied, backportPRNumber)

	if err := git.Run("commit", "-m", commitMsg); err != nil {
		return nil, fmt.Errorf("committing: %w", err)
	}
	if err := git.Run("push", "origin", workingBranch); err != nil {
		return nil, fmt.Errorf("pushing: %w", err)
	}

	body := fmt.Sprintf("Automated changelog sync from backport PR #%s.\n\nGenerated by the sync-backport-changelog workflow.", backportPRNumber)

	_, _, err = gh.Exec("pr", "create",
		"--base", "main",
		"--head", workingBranch,
		"--title", prTitle,
		"--label", "backport:sync-changelog",
		"--label", "changelog-link-check:skip",
		"--reviewer", "elastic/ecosystem",
		"--body", body,
	)
	if err != nil {
		return nil, fmt.Errorf("creating PR: %w", err)
	}

	_ = git.Run("checkout", backportBranch)
	return &SyncResult{NotFoundPackages: notFound, Outcome: "success"}, nil
}

type tsvEntry struct{ pkg, version, entryFile string }

func readEntriesTSV(path string) ([]tsvEntry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var entries []tsvEntry
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		parts := strings.SplitN(sc.Text(), "\t", 3)
		if len(parts) != 3 {
			continue
		}
		entries = append(entries, tsvEntry{pkg: parts[0], version: parts[1], entryFile: parts[2]})
	}
	return entries, sc.Err()
}

func buildCommitMessage(entries []tsvEntry, prNumber string) string {
	if len(entries) == 1 {
		return fmt.Sprintf("changelog: %s %s (backport sync from PR #%s)", entries[0].pkg, entries[0].version, prNumber)
	}
	return fmt.Sprintf("changelog: backport sync from PR #%s", prNumber)
}

func buildPRTitle(entries []tsvEntry, prNumber string) string {
	return buildCommitMessage(entries, prNumber)
}
