---
description: Pipeline for parsing HAProxy metrics.
processors:
  - remove:
      field: prometheus.metrics.up
      ignore_missing: true
  - remove:
      field: prometheus.labels
      ignore_missing: true
  - rename:
      field: prometheus.metrics
      target_field: haproxy.metrics
      ignore_missing: true
on_failure:
  - set:
      field: error.message
      value: "{{{_ingest.on_failure_message}}}"
