rules:
  - path: /remote/core.executeQuery
    methods: ['GET']
    query_params:
      target: 'EPOProductEvents'
      select: "{select:.*}"
      where: "{where:.*}"
      order: "{order:.*}"
      ':output': 'json'
    request_headers:
      Authorization:
        - "Basic eHh4eDp4eHh4"
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'text/plain'
        body: |-
          OK: [
            {
              "EPOProductEvents.AgentGUID": "89A1D5C1-2B3E-4F67-8A9B-0C1D2E3F4A5B",
              "EPOProductEvents.AutoID": 1,
              "EPOProductEvents.DetectedUTC": "2026-07-21T14:53:20+05:30",
              "EPOProductEvents.Error": 0,
              "EPOProductEvents.ExtraDATNames": null,
              "EPOProductEvents.HostName": "DESKTOP-K3QM7XP",
              "EPOProductEvents.IPV6": "2001:DB8:85A3:0:8A2E:370:7334:1",
              "EPOProductEvents.InitiatorID": null,
              "EPOProductEvents.InitiatorType": "CommandLine",
              "EPOProductEvents.Locale": 1033,
              "EPOProductEvents.NodeID": 1,
              "EPOProductEvents.ProductCode": "EPOAGENT3000",
              "EPOProductEvents.ReceivedUTC": "2026-07-21T14:53:47+05:30",
              "EPOProductEvents.SPHotFix": null,
              "EPOProductEvents.SiteName": null,
              "EPOProductEvents.TVDEventID": 2411,
              "EPOProductEvents.TVDSeverity": 0,
              "EPOProductEvents.TenantId": 1,
              "EPOProductEvents.Type": "Install",
              "EPOProductEvents.UserName": "SYSTEM"
            }
          ]
