---
description: "Pipeline for AWS CloudWatch metrics"
processors:
  - fingerprint:
      tag: fingerprint_0aa9a14c
      fields: ["aws.dimensions"]
      target_field: 'aws.dimensions_fingerprint'
      ignore_missing: true
on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: >-
        Processor '{{{ _ingest.on_failure_processor_type }}}'
        {{{#_ingest.on_failure_processor_tag}}}with tag '{{{ _ingest.on_failure_processor_tag }}}'
        {{{/_ingest.on_failure_processor_tag}}}in pipeline '{{{ _ingest.pipeline }}}' failed with message '{{{ _ingest.on_failure_message }}}'
