services:
  anduril_lattice:
    image: docker.elastic.co/observability/stream:v0.20.0
    hostname: anduril_lattice
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config-entity.yml
