server {
    listen 8080;

    # Mock of https://files.whoisfreaks.com/v3.1/download/domainer/gtld
    location /v3.1/download/domainer/gtld {
        default_type application/gzip;
        alias /usr/share/nginx/html/gtld;
    }
}

