variants:
  v9.2.4.0-r1-amd64:
    SERVICE_IMAGE: ibmcom/mq
    SERVICE_VERSION: 9.2.4.0-r1-amd64
  v9.4.0.20-r1:
    SERVICE_IMAGE: icr.io/ibm-messaging/mq
    SERVICE_VERSION: 9.4.0.20-r1
default: v9.4.0.20-r1
