---
description: Pipeline for parsing GCP Loadbalancing metrics.
processors:
  - fingerprint:
      tag: fingerprint_5c1d1252
      fields:
        - gcp.labels
      target_field: gcp.labels_fingerprint
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_https_backend_request_bytes_to_gcp_loadbalancing_metrics_https_backend_request_bytes_a6bfb0a4
      field: gcp.metrics.https.backend_request.bytes
      target_field: gcp.loadbalancing_metrics.https.backend_request.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_https_backend_request_count_to_gcp_loadbalancing_metrics_https_backend_request_count_fac9a9e4
      field: gcp.metrics.https.backend_request.count
      target_field: gcp.loadbalancing_metrics.https.backend_request.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_https_backend_response_bytes_to_gcp_loadbalancing_metrics_https_backend_response_bytes_5ca2cf84
      field: gcp.metrics.https.backend_response.bytes
      target_field: gcp.loadbalancing_metrics.https.backend_response.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_https_request_bytes_to_gcp_loadbalancing_metrics_https_request_bytes_a0a5e3b2
      field: gcp.metrics.https.request.bytes
      target_field: gcp.loadbalancing_metrics.https.request.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_https_request_count_to_gcp_loadbalancing_metrics_https_request_count_3033cf3a
      field: gcp.metrics.https.request.count
      target_field: gcp.loadbalancing_metrics.https.request.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_https_response_bytes_to_gcp_loadbalancing_metrics_https_response_bytes_4d37daf0
      field: gcp.metrics.https.response.bytes
      target_field: gcp.loadbalancing_metrics.https.response.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_l3_external_egress_bytes_to_gcp_loadbalancing_metrics_l3_external_egress_bytes_1427be40
      field: gcp.metrics.l3.external.egress.bytes
      target_field: gcp.loadbalancing_metrics.l3.external.egress.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_l3_external_egress_packets_count_to_gcp_loadbalancing_metrics_l3_external_egress_packets_count_6843f684
      field: gcp.metrics.l3.external.egress_packets.count
      target_field: gcp.loadbalancing_metrics.l3.external.egress_packets.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_l3_external_ingress_bytes_to_gcp_loadbalancing_metrics_l3_external_ingress_bytes_69a292e8
      field: gcp.metrics.l3.external.ingress.bytes
      target_field: gcp.loadbalancing_metrics.l3.external.ingress.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_l3_external_ingress_packets_count_to_gcp_loadbalancing_metrics_l3_external_ingress_packets_count_452f12bc
      field: gcp.metrics.l3.external.ingress_packets.count
      target_field: gcp.loadbalancing_metrics.l3.external.ingress_packets.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_l3_internal_egress_bytes_to_gcp_loadbalancing_metrics_l3_internal_egress_bytes_e2ed2ce4
      field: gcp.metrics.l3.internal.egress.bytes
      target_field: gcp.loadbalancing_metrics.l3.internal.egress.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_l3_internal_egress_packets_count_to_gcp_loadbalancing_metrics_l3_internal_egress_packets_count_9ce33958
      field: gcp.metrics.l3.internal.egress_packets.count
      target_field: gcp.loadbalancing_metrics.l3.internal.egress_packets.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_l3_internal_ingress_bytes_to_gcp_loadbalancing_metrics_l3_internal_ingress_bytes_fccbef44
      field: gcp.metrics.l3.internal.ingress.bytes
      target_field: gcp.loadbalancing_metrics.l3.internal.ingress.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_l3_internal_ingress_packets_count_to_gcp_loadbalancing_metrics_l3_internal_ingress_packets_count_6df75b68
      field: gcp.metrics.l3.internal.ingress_packets.count
      target_field: gcp.loadbalancing_metrics.l3.internal.ingress_packets.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_tcp_ssl_proxy_closed_connections_value_to_gcp_loadbalancing_metrics_tcp_ssl_proxy_closed_connections_value_09b04474
      field: gcp.metrics.tcp_ssl_proxy.closed_connections.value
      target_field: gcp.loadbalancing_metrics.tcp_ssl_proxy.closed_connections.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_tcp_ssl_proxy_egress_bytes_to_gcp_loadbalancing_metrics_tcp_ssl_proxy_egress_bytes_e4f53270
      field: gcp.metrics.tcp_ssl_proxy.egress.bytes
      target_field: gcp.loadbalancing_metrics.tcp_ssl_proxy.egress.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_tcp_ssl_proxy_ingress_bytes_to_gcp_loadbalancing_metrics_tcp_ssl_proxy_ingress_bytes_27cfbaaa
      field: gcp.metrics.tcp_ssl_proxy.ingress.bytes
      target_field: gcp.loadbalancing_metrics.tcp_ssl_proxy.ingress.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_tcp_ssl_proxy_new_connections_value_to_gcp_loadbalancing_metrics_tcp_ssl_proxy_new_connections_value_92fbdb14
      field: gcp.metrics.tcp_ssl_proxy.new_connections.value
      target_field: gcp.loadbalancing_metrics.tcp_ssl_proxy.new_connections.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_tcp_ssl_proxy_open_connections_value_to_gcp_loadbalancing_metrics_tcp_ssl_proxy_open_connections_value_0df0062c
      field: gcp.metrics.tcp_ssl_proxy.open_connections.value
      target_field: gcp.loadbalancing_metrics.tcp_ssl_proxy.open_connections.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_https_backend_latencies_value_to_gcp_loadbalancing_metrics_https_backend_latencies_value_89486802
      field: gcp.metrics.https.backend_latencies.value
      target_field: gcp.loadbalancing_metrics.https.backend_latencies.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_https_external_regional_backend_latencies_value_to_gcp_loadbalancing_metrics_https_external_regional_backend_latencies_value_1d3872d6
      field: gcp.metrics.https.external.regional.backend_latencies.value
      target_field: gcp.loadbalancing_metrics.https.external.regional.backend_latencies.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_https_external_regional_total_latencies_value_to_gcp_loadbalancing_metrics_https_external_regional_total_latencies_value_9a746d76
      field: gcp.metrics.https.external.regional.total_latencies.value
      target_field: gcp.loadbalancing_metrics.https.external.regional.total_latencies.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_https_frontend_tcp_rtt_value_to_gcp_loadbalancing_metrics_https_frontend_tcp_rtt_value_138d4634
      field: gcp.metrics.https.frontend_tcp_rtt.value
      target_field: gcp.loadbalancing_metrics.https.frontend_tcp_rtt.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_https_internal_backend_latencies_value_to_gcp_loadbalancing_metrics_https_internal_backend_latencies_value_aa22ff44
      field: gcp.metrics.https.internal.backend_latencies.value
      target_field: gcp.loadbalancing_metrics.https.internal.backend_latencies.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_https_internal_total_latencies_value_to_gcp_loadbalancing_metrics_https_internal_total_latencies_value_015d906c
      field: gcp.metrics.https.internal.total_latencies.value
      target_field: gcp.loadbalancing_metrics.https.internal.total_latencies.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_https_total_latencies_value_to_gcp_loadbalancing_metrics_https_total_latencies_value_d6c1b8e2
      field: gcp.metrics.https.total_latencies.value
      target_field: gcp.loadbalancing_metrics.https.total_latencies.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_l3_external_rtt_latencies_value_to_gcp_loadbalancing_metrics_l3_external_rtt_latencies_value_7d44194c
      field: gcp.metrics.l3.external.rtt_latencies.value
      target_field: gcp.loadbalancing_metrics.l3.external.rtt_latencies.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_l3_internal_rtt_latencies_value_to_gcp_loadbalancing_metrics_l3_internal_rtt_latencies_value_799173f0
      field: gcp.metrics.l3.internal.rtt_latencies.value
      target_field: gcp.loadbalancing_metrics.l3.internal.rtt_latencies.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_tcp_ssl_proxy_frontend_tcp_rtt_value_to_gcp_loadbalancing_metrics_tcp_ssl_proxy_frontend_tcp_rtt_value_b06e5188
      field: gcp.metrics.tcp_ssl_proxy.frontend_tcp_rtt.value
      target_field: gcp.loadbalancing_metrics.tcp_ssl_proxy.frontend_tcp_rtt.value
      ignore_missing: true
  - remove:
      tag: remove_ab6e04c7
      field:
        - gcp.metrics
      ignore_missing: true
on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: '{{{ _ingest.on_failure_message }}}'
