---
description: Pipeline for parsing GCP Dataproc metrics.
processors:
  - fingerprint:
      tag: fingerprint_5c1d1252
      fields:
        - gcp.labels
      target_field: gcp.labels_fingerprint
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_batch_spark_executors_count_to_gcp_dataproc_batch_spark_executors_count_8322ebf1
      field: gcp.metrics.batch.spark.executors.count
      target_field: gcp.dataproc.batch.spark.executors.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_hdfs_datanodes_count_to_gcp_dataproc_cluster_hdfs_datanodes_count_a279818d
      field: gcp.metrics.cluster.hdfs.datanodes.count
      target_field: gcp.dataproc.cluster.hdfs.datanodes.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_hdfs_storage_capacity_value_to_gcp_dataproc_cluster_hdfs_storage_capacity_value_8c6ba60d
      field: gcp.metrics.cluster.hdfs.storage_capacity.value
      target_field: gcp.dataproc.cluster.hdfs.storage_capacity.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_hdfs_storage_utilization_value_to_gcp_dataproc_cluster_hdfs_storage_utilization_value_12b8e11f
      field: gcp.metrics.cluster.hdfs.storage_utilization.value
      target_field: gcp.dataproc.cluster.hdfs.storage_utilization.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_hdfs_unhealthy_blocks_count_to_gcp_dataproc_cluster_hdfs_unhealthy_blocks_count_698842b1
      field: gcp.metrics.cluster.hdfs.unhealthy_blocks.count
      target_field: gcp.dataproc.cluster.hdfs.unhealthy_blocks.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_job_failed_count_to_gcp_dataproc_cluster_job_failed_count_1ef788c1
      field: gcp.metrics.cluster.job.failed.count
      target_field: gcp.dataproc.cluster.job.failed.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_job_running_count_to_gcp_dataproc_cluster_job_running_count_6eab8ff1
      field: gcp.metrics.cluster.job.running.count
      target_field: gcp.dataproc.cluster.job.running.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_job_submitted_count_to_gcp_dataproc_cluster_job_submitted_count_43515c51
      field: gcp.metrics.cluster.job.submitted.count
      target_field: gcp.dataproc.cluster.job.submitted.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_operation_failed_count_to_gcp_dataproc_cluster_operation_failed_count_6fd38b8d
      field: gcp.metrics.cluster.operation.failed.count
      target_field: gcp.dataproc.cluster.operation.failed.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_operation_running_count_to_gcp_dataproc_cluster_operation_running_count_b205ba09
      field: gcp.metrics.cluster.operation.running.count
      target_field: gcp.dataproc.cluster.operation.running.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_operation_submitted_count_to_gcp_dataproc_cluster_operation_submitted_count_8fe718e1
      field: gcp.metrics.cluster.operation.submitted.count
      target_field: gcp.dataproc.cluster.operation.submitted.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_yarn_allocated_memory_percentage_value_to_gcp_dataproc_cluster_yarn_allocated_memory_percentage_value_59211379
      field: gcp.metrics.cluster.yarn.allocated_memory_percentage.value
      target_field: gcp.dataproc.cluster.yarn.allocated_memory_percentage.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_yarn_apps_count_to_gcp_dataproc_cluster_yarn_apps_count_7f8a9d51
      field: gcp.metrics.cluster.yarn.apps.count
      target_field: gcp.dataproc.cluster.yarn.apps.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_yarn_containers_count_to_gcp_dataproc_cluster_yarn_containers_count_a4211c85
      field: gcp.metrics.cluster.yarn.containers.count
      target_field: gcp.dataproc.cluster.yarn.containers.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_yarn_memory_size_value_to_gcp_dataproc_cluster_yarn_memory_size_value_95277d37
      field: gcp.metrics.cluster.yarn.memory_size.value
      target_field: gcp.dataproc.cluster.yarn.memory_size.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_yarn_nodemanagers_count_to_gcp_dataproc_cluster_yarn_nodemanagers_count_ed56e85d
      field: gcp.metrics.cluster.yarn.nodemanagers.count
      target_field: gcp.dataproc.cluster.yarn.nodemanagers.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_yarn_pending_memory_size_value_to_gcp_dataproc_cluster_yarn_pending_memory_size_value_f432c14f
      field: gcp.metrics.cluster.yarn.pending_memory_size.value
      target_field: gcp.dataproc.cluster.yarn.pending_memory_size.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_yarn_virtual_cores_count_to_gcp_dataproc_cluster_yarn_virtual_cores_count_5318d1fd
      field: gcp.metrics.cluster.yarn.virtual_cores.count
      target_field: gcp.dataproc.cluster.yarn.virtual_cores.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_job_completion_time_value_to_gcp_dataproc_cluster_job_completion_time_value_f7dac489
      field: gcp.metrics.cluster.job.completion_time.value
      target_field: gcp.dataproc.cluster.job.completion_time.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_job_duration_value_to_gcp_dataproc_cluster_job_duration_value_ce3a4ecb
      field: gcp.metrics.cluster.job.duration.value
      target_field: gcp.dataproc.cluster.job.duration.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_operation_completion_time_value_to_gcp_dataproc_cluster_operation_completion_time_value_dacdd3ed
      field: gcp.metrics.cluster.operation.completion_time.value
      target_field: gcp.dataproc.cluster.operation.completion_time.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_cluster_operation_duration_value_to_gcp_dataproc_cluster_operation_duration_value_645d5c13
      field: gcp.metrics.cluster.operation.duration.value
      target_field: gcp.dataproc.cluster.operation.duration.value
      ignore_missing: true
  - remove:
      tag: remove_ab6e04c7
      ignore_missing: true
      field:
        - gcp.metrics

on_failure:
  - set:
      tag: set_event_kind
      field: event.kind
      value: pipeline_error
  - append:
      tag: append_error_message
      field: error.message
      value: '{{{ _ingest.on_failure_message }}}'
  - append:
      tag: append_tags
      field: tags
      value: preserve_original_event
      allow_duplicates: false
