#!/usr/bin/env bash
# Regenerate CrowdStrike FDR ingest pipelines from the Go generators in this directory.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$(cd "${SCRIPT_DIR}/../../../data_stream/fdr/elasticsearch/ingest_pipeline" && pwd)"

HEADER_LINE1='# Generated by packages/crowdstrike/_dev/scripts/fdr-gen. Do not edit by hand.'
HEADER_LINE2='# Regenerate with: ./generate.sh (from that directory)'

die() {
  echo "error: $*" >&2
  exit 1
}

require_go() {
  if ! command -v go >/dev/null 2>&1; then
    die "go is required but was not found on PATH. Install Go from https://go.dev/dl/ and retry."
  fi

  local required
  required="$(awk '/^go / { print $2; exit }' "${SCRIPT_DIR}/go.mod")"
  if [[ -n "${required}" ]]; then
    local installed
    installed="$(go env GOVERSION 2>/dev/null | sed 's/^go//' || true)"
    if [[ -z "${installed}" ]]; then
      installed="$(go version | awk '{ print $3 }' | sed 's/^go//')"
    fi
    # Warn when the installed major.minor is older than the module's go directive.
    local req_mm inst_mm
    req_mm="$(echo "${required}" | awk -F. '{ print $1"."$2 }')"
    inst_mm="$(echo "${installed}" | awk -F. '{ print $1"."$2 }')"
    if [[ "$(printf '%s\n%s\n' "${req_mm}" "${inst_mm}" | sort -V | head -n1)" != "${req_mm}" ]]; then
      echo "warning: go ${installed} is older than go.mod requirement ${required}; generation may fail." >&2
    fi
  fi
}

# Strip a previous fdr-gen header (if present) so re-runs stay idempotent,
# then place headers immediately after the leading '---' (package-spec requires
# document dashes as the first line).
write_with_header() {
  local src="$1"
  local dest="$2"
  local tmp
  tmp="$(mktemp)"

  awk -v h1="${HEADER_LINE1}" -v h2="${HEADER_LINE2}" '
    BEGIN { after_doc = 0; skipping_old = 0 }
    /^---$/ && !after_doc {
      print
      print h1
      print h2
      after_doc = 1
      skipping_old = 1
      next
    }
    skipping_old && /^# Generated by packages\/crowdstrike\// { next }
    skipping_old && /^# Regenerate with: \.\/generate\.sh/ { next }
    skipping_old && /^$/ { next }
    { skipping_old = 0; print }
  ' "${src}" >"${tmp}"

  mv "${tmp}" "${dest}"
}

run_one() {
  local label="$1"
  shift
  local dest="$1"
  shift

  local tmp
  tmp="$(mktemp)"
  echo "Generating ${label} -> $(basename "${dest}")"
  if ! (cd "${SCRIPT_DIR}" && go run "$@" -out "${tmp}"); then
    rm -f "${tmp}"
    die "failed generating ${label}"
  fi
  write_with_header "${tmp}" "${dest}"
  rm -f "${tmp}"
}

require_go

cd "${SCRIPT_DIR}"
echo "Downloading Go module dependencies..."
go mod download

mkdir -p "${OUT_DIR}"

run_one "default" "${OUT_DIR}/default.yml" default.go
run_one "categorize" "${OUT_DIR}/categorize.yml" categorize.go
run_one "inbound_network" "${OUT_DIR}/inbound_network.yml" network.go -dir inbound
run_one "outbound_network" "${OUT_DIR}/outbound_network.yml" network.go -dir outbound
run_one "automated_lead_summary" "${OUT_DIR}/automated_lead_summary.yml" automated_lead_summary.go
run_one "epp_detection_summary" "${OUT_DIR}/epp_detection_summary.yml" epp_detection_summary.go
run_one "data_protection_detection_summary" "${OUT_DIR}/data_protection_detection_summary.yml" data_protection.go
run_one "fim_rule_matched" "${OUT_DIR}/fim_rule_matched.yml" fim_rule_matched.go
run_one "cspm_iom" "${OUT_DIR}/cspm_iom.yml" cspm_iom.go
run_one "cspm_ioa" "${OUT_DIR}/cspm_ioa.yml" cspm_ioa.go

echo "Done. Pipelines written to ${OUT_DIR}"
