---
description: Pipeline for processing and enriching Entro audit logs according to ECS.
processors:
  - set:
      field: ecs.version
      tag: set_ecs_version
      value: '8.17.0'
  - terminate:
      tag: data_collection_error
      if: ctx.error?.message != null && ctx.message == null && ctx.event?.original == null
      description: error message set and no data to process.
  - date:
      field: date
      target_field: '@timestamp'
      formats:
        - ISO8601
      timezone: UTC
      tag: date_parse_timestamp
      if: ctx.date != null
      on_failure:
        - remove:
            tag: remove_date_1a15cc9b
            field: date
        - append:
            tag: append_error_message_bf1997ac
            field: error.message
            value: >-
                Processor '{{{ _ingest.on_failure_processor_type }}}'
                {{{#_ingest.on_failure_processor_tag}}}with tag '{{{ _ingest.on_failure_processor_tag }}}'
                {{{/_ingest.on_failure_processor_tag}}}failed with message '{{{ _ingest.on_failure_message }}}'
  - fingerprint:
      fields:
        - request_id
        - secret_type
        - exposed_value
        - date
      tag: fingerprint
      target_field: _id
      ignore_missing: true
  - set:
      tag: set_event_id_7cf3f855
      field: event.id
      copy_from: request_id
      ignore_empty_value: true
  - set:
      tag: set_vulnerability_value_d873757a
      field: vulnerability.value
      copy_from: exposed_value
      ignore_empty_value: true
  - set:
      tag: set_log_origin_file_line_d1fd2935
      field: log.origin.file.line
      copy_from: line_number
      ignore_empty_value: true
  - set:
      tag: set_vulnerability_category_31985606
      field: vulnerability.category
      value: ["Secret"]
      ignore_empty_value: true
      if: ctx.secret_type != null
  - set:
      tag: set_vulnerability_description_a3826a5e
      field: vulnerability.description
      copy_from: secret_type
      ignore_empty_value: true
  - set:
      tag: set_event_kind_de80643c
      field: event.kind
      value: event
  - set:
      tag: set_event_category_13b30ef2
      field: event.category
      value: ["vulnerability"]
  - set:
      tag: set_event_type_ec95f7f2
      field: event.type
      value: ["info"]
  - set:
      tag: set_event_dataset_d3e82901
      field: event.dataset
      value: "entro.audit"
  - remove:
      tag: remove_07170528
      field:
        - date
        - request_id
        - secret_type
        - line_number
        - exposed_value
      ignore_missing: true
on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: tags
      value: preserve_original_event
      allow_duplicates: false
  - append:
      field: error.message
      value: >-
        Processor '{{{ _ingest.on_failure_processor_type }}}'
        {{{#_ingest.on_failure_processor_tag}}}with tag '{{{ _ingest.on_failure_processor_tag }}}'
        {{{/_ingest.on_failure_processor_tag}}}failed with message '{{{ _ingest.on_failure_message }}}'
