---
description: "Pipeline for logs ingested from CloudWatch"

processors:
  - set:
      tag: set_ecs_version_0f7334bb
      field: ecs.version
      value: '8.11.0'
  - set:
      tag: set_event_original_6f8a8b2e
      field: event.original
      copy_from: message
      ignore_empty_value: true
      if: 'ctx.event?.original == null'
  - set:
      tag: set_cloud_provider_208bdd6b
      field: cloud.provider
      value: aws
  - set:
      tag: set_event_kind_de80643c
      field: event.kind
      value: event
  - set:
      tag: set_timestamp_0ab892ee
      field: '@timestamp'
      value: "{{{_ingest.timestamp}}}"
      override: false
on_failure:
  - set:
      tag: set_event_kind_72b1902f
      field: event.kind
      value: pipeline_error
  - append:
      tag: append_error_message_14080786
      field: error.message
      value: >-
        Processor '{{{ _ingest.on_failure_processor_type }}}'
        {{{#_ingest.on_failure_processor_tag}}}with tag '{{{ _ingest.on_failure_processor_tag }}}'
        {{{/_ingest.on_failure_processor_tag}}}in pipeline '{{{ _ingest.pipeline }}}' failed with message '{{{ _ingest.on_failure_message }}}'
  - append:
      tag: append_tags_279d5a5c
      field: tags
      value: preserve_original_event
      allow_duplicates: false
