---
description: Pipeline for processing OpenAI rate limits.
processors:
  - set:
      field: ecs.version
      tag: set_ecs_version
      value: '9.3.0'
  - set:
      field: event.kind
      tag: set_event_kind
      value: metric
  - rename:
      field: message
      tag: rename_message_to_results
      target_field: openai.rate_limits.results
      ignore_missing: true
      if: ctx.event?.original == null
  - remove:
      field: message
      tag: remove_message
      ignore_missing: true
      if: ctx.event?.original != null
  - json:
      field: openai.rate_limits.results
      tag: json_results
      target_field: openai.rate_limits
      if: ctx.openai?.rate_limits?.results != null
  - remove:
      field: openai.rate_limits.results
      tag: remove_results
      ignore_missing: true
  - date:
      field: openai.rate_limits.collected_at
      tag: date_collected_at
      target_field: '@timestamp'
      formats:
        - ISO8601
      ignore_failure: true
      if: ctx.openai?.rate_limits?.collected_at != null
  - set:
      field: event.created
      tag: set_event_created
      copy_from: '@timestamp'
      ignore_empty_value: true
  - set:
      field: event.kind
      tag: set_pipeline_error_into_event_kind
      value: pipeline_error
      if: ctx.error?.message != null
  - append:
      field: tags
      tag: append_preserve_original_event_tag
      value: preserve_original_event
      allow_duplicates: false
      if: ctx.error?.message != null

###################
# Failure handler #
###################
on_failure:
  - append:
      tag: append_error_message
      field: error.message
      value: |
        Processor '{{{ _ingest.on_failure_processor_type }}}'
        with tag '{{{ _ingest.on_failure_processor_tag }}}'
        in pipeline '{{{ _ingest.on_failure_pipeline }}}'
        failed with message '{{{ _ingest.on_failure_message }}}'
  - set:
      tag: set_event_kind_pipeline_error
      field: event.kind
      value: pipeline_error
  - append:
      field: tags
      tag: append_preserve_original_event
      value: preserve_original_event
      allow_duplicates: false
