rules:
  #### UserAudits ####
  - path: "/BeyondTrust/api/public/v3/Auth/SignAppin"
    methods: ["POST"]
    request_headers:
      Authorization: ['PS-Auth key=abcd1234byiapitoken;runas=testuser;pwd=\[password\];']
      Content-Type: ['application/json']
    responses:
      - status_code: 200
        headers:
          Content-Type: ['application/json']
          Set-Cookie: ['ASP.NET_SessionId=iijfdzn51fdh01axylh1nnd1']
        body: |
          {
            "UserId": 1,
            "SID": null,
            "EmailAddress": "test.user@example.com",
            "UserName": "testuser",
            "Name": "Test User"
          }
  - path: "/BeyondTrust/api/public/v3/UserAudits"
    methods: ["GET"]
    request_headers:
      Content-Type: ['application/json']
      Cookie: ['ASP.NET_SessionId=iijfdzn51fdh01axylh1nnd1']
    responses:
      - status_code: 200
        headers:
          Content-Type: ['application/json']
        body: |
          {
            "TotalCount": 4,
            "Data": [
              {
                "AuditID": 4,
                "ActionType": "Login",
                "Section": "PMM API SignAppIn",
                "UserID": 6,
                "UserName": "test.user@example.com",
                "IPAddress": "216.160.83.56",
                "CreateDate": "2024-12-16T10:24:26.323Z"
              },
              {
                "AuditID": 3,
                "ActionType": "Login",
                "Section": "PMM API SignAppIn",
                "UserID": 6,
                "UserName": "test.user@example.com",
                "IPAddress": "216.160.83.56",
                "CreateDate": "2024-12-12T10:24:26.323Z"
              },
              {
                "AuditID": 2,
                "ActionType": "Login",
                "Section": "PMM API SignAppIn",
                "UserID": 6,
                "UserName": "test.user@example.com",
                "IPAddress": "216.160.83.56",
                "CreateDate": "2024-12-11T10:24:26.323Z"
              },
              {
                "AuditID": 1,
                "ActionType": "Login",
                "Section": "PMM API SignAppIn",
                "UserID": 6,
                "UserName": "test.user@example.com",
                "IPAddress": "216.160.83.56",
                "CreateDate": "2024-12-09T10:24:26.323Z"
              }
            ]
          }
  - path: "/BeyondTrust/api/public/v3/Sessions"
    methods: ["GET"]
    request_headers:
      Content-Type: ['application/json']
      Cookie: ['ASP.NET_SessionId=iijfdzn51fdh01axylh1nnd1']
    responses:
      - status_code: 200
        headers:
          Content-Type: ['application/json']
        body: |
          [
            {
              "SessionID": 1,
              "UserID": 6,
              "NodeID": "a5c29153-b351-41f1-a12b-0c4da9408d79",
              "Status": 0,
              "ArchiveStatus": 0,
              "Protocol": 0,
              "StartTime": null,
              "EndTime": null,
              "Duration": 0,
              "AssetName": "localhost",
              "ManagedSystemID": 13,
              "ManagedAccountID": null,
              "ManagedAccountName": "example.com\\sdfsfdf",
              "RecordKey": "3958d725d16119a95e64af424a7f8dfsf13f1fgffbe4a6cd34earwr324454bcecce70ee37cbaed",
              "Token": "bcb8c654b827a4465846c96b5d6dd8dsfsdf2935c6ahhgg1f02f067fd0976dfsdf6d7370c22"
            }
          ]
  - path: "/BeyondTrust/api/public/v3/ManagedAccounts"
    methods: ["GET"]
    request_headers:
      Content-Type: ['application/json']
      Cookie: ['ASP.NET_SessionId=iijfdzn51fdh01axylh1nnd1']
    responses:
      - status_code: 200
        headers:
          Content-Type: ['application/json']
        body: |
          [
              {
                  "PlatformID": 4,
                  "SystemId": 5,
                  "SystemName": "KittenGrowth",
                  "InstanceName": "Primary",
                  "DomainName": "example.com",
                  "AccountId": 5,
                  "AccountName": "MacdonaldP.Irene",
                  "UserPrincipalName": "irene@example.com",
                  "ApplicationID": 123,
                  "ApplicationDisplayName": "AccountingApp",
                  "MaximumReleaseDuration": 525600,
                  "DefaultReleaseDuration": 120,
                  "LastChangeDate": "2024-12-10T08:57:45.9",
                  "NextChangeDate": "2024-12-12T00:00:00.0",
                  "ChangeState": 2,
                  "IsChanging": false,
                  "IsISAAccess": true,
                  "PreferredNodeID": "2ca45774-d4e0-4b8f-9b52-3f52b78ae2ca"
              }
          ]
  - path: "/BeyondTrust/api/public/v3/ManagedSystems"
    methods: ["GET"]
    request_headers:
      Content-Type: ['application/json']
      Cookie: ['ASP.NET_SessionId=iijfdzn51fdh01axylh1nnd1']
    responses:
      - status_code: 200
        headers:
          Content-Type: ['application/json']
        body: |
          { "TotalCount": 1, "Data": [  {"ManagedSystemID": 13,"EntityTypeID": 1,"AssetID": 13,"DatabaseID": null,"DirectoryID": null,"CloudID": null,"WorkgroupID": 1,"HostName": "AardvarkAgreement","DnsName": "AardvarkAgreement.example.com","IPAddress": "172.16.152.110","InstanceName": null,"IsDefaultInstance": null,"Template": null,"ForestName": null,"UseSSL": null,"OracleInternetDirectoryID": null,"OracleInternetDirectoryServiceName": null,"SystemName": "AardvarkAgreement","PlatformID": 4,"NetBiosName": null,"Port": null,"Timeout": 30,"Description": null,"ContactEmail": null,"PasswordRuleID": 0,"DSSKeyRuleID": 0,"ReleaseDuration": 120,"MaxReleaseDuration": 525600,"ISAReleaseDuration": 120,"AutoManagementFlag": true,"FunctionalAccountID": 14,"LoginAccountID": null,"ElevationCommand": null,"SshKeyEnforcementMode": 0,"CheckPasswordFlag": false,"ChangePasswordAfterAnyReleaseFlag": false,"ResetPasswordOnMismatchFlag": false,"ChangeFrequencyType": "first","ChangeFrequencyDays": 30,"ChangeTime": "23:30","AccountNameFormat": 0,"RemoteClientType": "None","ApplicationHostID": null,"IsApplicationHost": false,"AccessURL": null   }]}
  - path: "/BeyondTrust/api/public/v3/Workgroups"
    methods: [ "GET" ]
    request_headers:
      Cookie: [ 'ASP.NET_SessionId=iijfdzn51fdh01axylh1nnd1' ]
    responses:
      - status_code: 200
        headers:
          Content-Type: [ 'application/json' ]
        body: |
          [
           {
               "OrganizationID": "abcd27cf-791a-4c65-abe9-a6a250b8e4f6",
               "ID": 1,
               "Name": "Default Workgroup"
           }
          ]
  - path: "/BeyondTrust/api/public/v3/Workgroups/1/Assets"
    methods: [ "GET" ]
    request_headers:
      Cookie: [ 'ASP.NET_SessionId=iijfdzn51fdh01axylh1nnd1' ]
    responses:
      - status_code: 200
        headers:
          Content-Type: [ 'application/json' ]
        body: |
          {
           "TotalCount": 1,
           "Data": [
               {
                   "WorkgroupID": 1,
                   "AssetID": 2,
                   "AssetName": "EPINHYDW002A",
                   "AssetType": "WorkStation",
                   "DnsName": "EPINHYDW002A",
                   "DomainName": "Unknown",
                   "IPAddress": "192.168.29.50",
                   "OperatingSystem": "Windows 11 Enterprise",
                   "CreateDate": "2024-11-20T06:12:21.047Z",
                   "LastUpdateDate": "2024-11-20T06:35:49.927Z"
               }
          ]
          }