---
description: Pipeline for renaming object
processors:
  - set:
      field: ecs.version
      value: "8.11.0"
  - json:
      field: mailboxquotastatus
      target_field: o365metrics.mailboxquotastatus   
  - script:
      lang: painless
      description: Replace spaces and dashes in field names under o365metrics.mailboxquotastatus.
      tag: painless_purge_spaces_and_dashes
      if: ctx.o365metrics?.mailboxquotastatus instanceof Map
      source: |
        String underscore(String s) {
          return /[ -]/.matcher(s).replaceAll('_').toLowerCase();
        }
        
        def out = [:];
        for (def item : ctx.o365metrics.mailboxquotastatus.entrySet()) {
          out[underscore(item.getKey())] = item.getValue();
        }
        ctx.o365metrics.mailboxquotastatus = out;

  - remove:
      if: ctx.mailboxquotastatus != null
      field: mailboxquotastatus
      ignore_missing: true                               

on_failure:
  - append:
      field: error.message
      value: "{{{_ingest.on_failure_message}}}"
  - append:
      field: event.kind
      value: pipeline_error
      allow_duplicates: false
