fields:
  - name: timestamp
    period: -24h
  - name: account_id
    cardinality: 100
  - name: forensic_copy_id
    cardinality: 100000
  - name: gateway_request_id
    cardinality: 100000
  - name: payload
    cardinality: 10000
  - name: phase
    enum:
      - request
      - response
  - name: triggered_rule_id
    cardinality: 1000
