fields:
  - name: timestamp
    period: -24h
  - name: asset_display_name
    cardinality: 5000
  - name: asset_external_id
    cardinality: 5000
  - name: finding_type_display_name
    enum:
      - "Salesforce User Sending Email with Different Email Address"
      - "Google Drive File Shared Publicly"
      - "Slack Channel with External Members"
      - "Microsoft 365 Suspicious Login"
  - name: finding_type_id
    cardinality: 100
  - name: finding_type_severity
    enum:
      - Low
      - Medium
      - High
      - Critical
  - name: instance_id
    cardinality: 1000
  - name: integration_display_name
    enum:
      - "Salesforce Testing"
      - "Google Workspace Prod"
      - "Microsoft 365 Prod"
      - "Slack Enterprise"
  - name: integration_id
    cardinality: 100
  - name: integration_policy_vendor
    enum:
      - "Salesforce Connection"
      - "Google Workspace Connection"
      - "Microsoft 365 Connection"
      - "Slack Connection"
