rules:
  - path: /v1/organization/audit_logs
    methods: ['GET']
    query_params:
      limit: 2
      before: "audit_log-iakaJWnLdMLe89Ml5xayb4RJ"
    request_headers:
      Authorization:
        - "Bearer xxxx"
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {{ minify_json `
          {
            "data": [
              {
                  "object": "organization.audit_log",
                  "id": "audit_log-rtC0QjFGRIaZskr6ZCBkC6kM",
                  "type": "login.succeeded",
                  "effective_at": 1770979925,
                  "actor": {
                      "type": "session",
                      "session": {
                          "user": {
                              "id": "user-nuEwi8Vsrrddq53RTzEQ9p3c",
                              "email": "muskan.agarwal@crestdata.ai"
                          },
                          "ip_address": "163.116.213.158",
                          "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
                          "ja3": "353a03072e841d5004dfaa78561ccc70",
                          "ja4": "t13d691100_8b2139ff7677_f0e8fcc46740",
                          "ip_address_details": {
                              "country": "IN",
                              "city": "Mumbai",
                              "region": "Maharashtra",
                              "region_code": "MH",
                              "asn": "55256",
                              "latitude": "19.07283",
                              "longitude": "72.88261"
                          }
                      }
                  }
              },
              {
                  "object": "organization.audit_log",
                  "id": "audit_log-rtkaJWnLdMLe89Ml5xayb4RJ",
                  "type": "login.succeeded",
                  "effective_at": 1770616227,
                  "actor": {
                      "type": "session",
                      "session": {
                          "user": {
                              "id": "user-nuEwi8Vsrrddq53RTzEQ9p3c",
                              "email": "muskan.agarwal@crestdata.ai"
                          },
                          "ip_address": "163.116.213.142",
                          "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
                          "ja3": "353a03072e841d5004dfaa78561ccc70",
                          "ja4": "t13d691100_8b2139ff7677_f0e8fcc46740",
                          "ip_address_details": {
                              "country": "IN",
                              "city": "Mumbai",
                              "region": "Maharashtra",
                              "region_code": "MH",
                              "asn": "55256",
                              "latitude": "19.07283",
                              "longitude": "72.88261"
                          }
                      }
                  }
              }
            ],
            "first_id": "audit_log-rtC0QjFGRIaZskr6ZCBkC6kM",
            "last_id": "audit_log-rtkaJWnLdMLe89Ml5xayb4RJ",
            "has_more": false
          }
          `}}
  - path: /v1/organization/audit_logs
    methods: ['GET']
    query_params:
      limit: 2
    request_headers:
      Authorization:
        - "Bearer xxxx"
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {{ minify_json `
          {
            "data": [
              {
                  "object": "organization.audit_log",
                  "id": "audit_log-C7C0QjFGRIaZskr6ZCBkC6kM",
                  "type": "login.succeeded",
                  "effective_at": 1770979925,
                  "actor": {
                      "type": "session",
                      "session": {
                          "user": {
                              "id": "user-nuEwi8Vsrrddq53RTzEQ9p3c",
                              "email": "muskan.agarwal@crestdata.ai"
                          },
                          "ip_address": "163.116.213.158",
                          "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
                          "ja3": "353a03072e841d5004dfaa78561ccc70",
                          "ja4": "t13d691100_8b2139ff7677_f0e8fcc46740",
                          "ip_address_details": {
                              "country": "IN",
                              "city": "Mumbai",
                              "region": "Maharashtra",
                              "region_code": "MH",
                              "asn": "55256",
                              "latitude": "19.07283",
                              "longitude": "72.88261"
                          }
                      }
                  }
              },
              {
                  "object": "organization.audit_log",
                  "id": "audit_log-iakaJWnLdMLe89Ml5xayb4RJ",
                  "type": "login.succeeded",
                  "effective_at": 1770616227,
                  "actor": {
                      "type": "session",
                      "session": {
                          "user": {
                              "id": "user-nuEwi8Vsrrddq53RTzEQ9p3c",
                              "email": "muskan.agarwal@crestdata.ai"
                          },
                          "ip_address": "163.116.213.142",
                          "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
                          "ja3": "353a03072e841d5004dfaa78561ccc70",
                          "ja4": "t13d691100_8b2139ff7677_f0e8fcc46740",
                          "ip_address_details": {
                              "country": "IN",
                              "city": "Mumbai",
                              "region": "Maharashtra",
                              "region_code": "MH",
                              "asn": "55256",
                              "latitude": "19.07283",
                              "longitude": "72.88261"
                          }
                      }
                  }
              }
            ],
            "first_id": "audit_log-C7C0QjFGRIaZskr6ZCBkC6kM",
            "last_id": "audit_log-iakaJWnLdMLe89Ml5xayb4RJ",
            "has_more": true
          }
          `}}
