services:
  jaeger_trace_sender:
    build: .
    environment:
      JAEGER_PROTOCOL: ${JAEGER_PROTOCOL:-grpc}
      JAEGER_GRPC_TARGET: ${JAEGER_GRPC_TARGET:-elastic-agent:14250}
      JAEGER_ENDPOINT: ${JAEGER_ENDPOINT:-http://elastic-agent:14268/api/traces}
      JAEGER_UDP_TARGET: ${JAEGER_UDP_TARGET:-elastic-agent:6831}
      OTEL_SERVICE_NAME: test-service
