#!/usr/bin/env sh

set -ex

TARGET_URL=${TARGET_URL:-http://backend:9000}

# NOTE: it cannot be done using SIGHUP signal, since the backend container is also
# killed and the traces would not be sent to the elastic-agent container.

# Wait for the elastic-agent container to be ready with the corresponding
# agent policy assigned
sleep 20

echo "Sending traces to ${TARGET_URL}/api"
i=0
while true; do
    echo "Trigger query ${i}"
    # Force creating traces containing requests with errors
    # The following curl command will fail with a 404 error per the backend code.
    # FIXME: Currently, the traces generated by the backend with errors cause that system tests fail.
    # curl "${TARGET_URL}"; sleep 1;

    ## Create traces without any errors
    # curl ${TARGET_URL}/api will return a 200 status code
    curl -s -o /dev/null "${TARGET_URL}/api"; sleep 1;
    i=$((i+1))
done
