#!/usr/bin/env sh

set -ex

TARGET_URL=${TARGET_URL:-http://backend:9000}
SLEEP_TIME=${SLEEP_TIME:-5}

# NOTE: backend container is the one that requires to communicate with the elastic-agent container
# to send the traces to the zipkin receiver port. If set the SIGHUP signal in the test system configuration
# file, that signal would be received by the backend container and it gets killed.
# Therefore, the SIGHUP signal is not used to start the workload and it is done here instead (separate container).

# Wait for the elastic-agent container to be ready with the corresponding
# agent policy assigned
sleep ${SLEEP_TIME}

echo "Sending traces to ${TARGET_URL}/api"
i=0
while true; do
    echo "Trigger query ${i}"
    # Force creating traces containing requests with errors
    # The following curl command will fail with a 404 error per the backend code.
    # FIXME: Currently, the traces generated by the backend with errors cause that system tests fail.
    # curl -s -o /dev/null "${TARGET_URL}"; sleep 1;

    ## Create traces without any errors
    # curl ${TARGET_URL}/api will return a 200 status code
    curl -s -o /dev/null "${TARGET_URL}/api"; sleep 1;
    i=$((i+1))
done
