services:
  trellix_epo_on_prem_compliance_history:
    image: docker.elastic.co/observability/stream:v0.22.0
    hostname: trellix_epo_on_prem_compliance_history
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config.yml
