version: '3.8'
services:
  trellix_epo_on_prem:
    image: docker.elastic.co/observability/stream:v0.22.0
    hostname: trellix_epo_on_prem
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config.yml
  trellix_epo_on_prem-event-tcp:
    image: docker.elastic.co/observability/stream:v0.22.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9514 -p=tcp /sample_logs/trellix_epo_on_prem-event.log
  trellix_epo_on_prem-event-udp:
    image: docker.elastic.co/observability/stream:v0.22.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9514 -p=udp /sample_logs/trellix_epo_on_prem-event.log
