---
description: Pipeline for Google Cloud DNS logs
processors:
  - set:
      tag: set_ecs_version_0f7334bb
      field: ecs.version
      value: '8.11.0'
  - rename:
      tag: rename_message_to_event_original_56a77271
      field: message
      target_field: event.original
      ignore_missing: true
      if: 'ctx.event?.original == null'
  - json:
      tag: json_event_original_to_json_5e54dc16
      field: event.original
      target_field: json
  - set:
      tag: set_event_kind_de80643c
      field: event.kind
      value: event
  - set:
      tag: set_event_category_dbab8a4e
      field: event.category
      value: ["network"]
  - set:
      tag: set_event_action_67c39ee2
      field: event.action
      value: dns-query
  - set:
      tag: set_cloud_provider_62c5e42e
      field: cloud.provider
      value: gcp
  - date:
      tag: date_json_timestamp_e111e976
      field: json.timestamp
      timezone: UTC
      formats:
        - ISO8601
  - set:
      tag: set_log_logger_01230fab
      field: log.logger
      copy_from: json.logName
      ignore_failure: true
  - set:
      tag: set_log_level_d2cd6285
      field: log.level
      copy_from: json.severity
      ignore_failure: true
  - set:
      tag: set_event_id_efd37a25
      field: event.id
      copy_from: json.insertId
      ignore_empty_value: true
      ignore_failure: true
  - convert:
      tag: convert_json_resource_labels_project_id_to_cloud_project_id_390fb252
      field: json.resource.labels.project_id
      target_field: cloud.project.id
      type: string
      ignore_missing: true
      ignore_failure: true
  - convert:
      tag: convert_json_resource_labels_location_to_cloud_region_f1d4aea1
      field: json.resource.labels.location
      target_field: cloud.region
      type: string
      ignore_failure: true
  - set:
      tag: set_gcp_dns_auth_answer_c0273364
      field: gcp.dns.auth_answer
      copy_from: json.jsonPayload.authAnswer
      ignore_failure: true
  - set:
      tag: set_gcp_dns_destination_ip_7b975d80
      field: gcp.dns.destination_ip
      copy_from: json.jsonPayload.destinationIP
      ignore_failure: true
  - set:
      tag: set_destination_address_6248e853
      field: destination.address
      copy_from: gcp.dns.destination_ip
      ignore_failure: true
  - convert:
      tag: convert_gcp_dns_destination_ip_to_destination_ip_8202a074
      field: gcp.dns.destination_ip
      target_field: destination.ip
      type: ip
      ignore_failure: true
  - set:
      tag: set_gcp_dns_egress_error_07d3554c
      field: gcp.dns.egress_error
      copy_from: json.jsonPayload.egressError
      ignore_failure: true
  - set:
      tag: set_gcp_dns_protocol_4a5570bf
      field: gcp.dns.protocol
      copy_from: json.jsonPayload.protocol
      ignore_failure: true
  - set:
      tag: set_network_transport_0322102e
      field: network.transport
      copy_from: gcp.dns.protocol
      ignore_failure: true
  - lowercase:
      tag: lowercase_network_transport_bc8c1c12
      field: network.transport
      ignore_missing: true
  - set:
      tag: set_network_iana_number_c83eed1a
      field: network.iana_number
      value: '6'
      if: ctx.network?.transport == "tcp"
  - set:
      tag: set_network_iana_number_c552b054
      field: network.iana_number
      value: '17'
      if: ctx.network?.transport == "udp"
  - set:
      tag: set_network_protocol_96a840d1
      field: network.protocol
      value: dns
  - set:
      tag: set_gcp_dns_query_name_1ed212b0
      field: gcp.dns.query_name
      copy_from: json.jsonPayload.queryName
      ignore_failure: true
  - set:
      tag: set_dns_question_name_834cf51f
      field: dns.question.name
      copy_from: gcp.dns.query_name
      ignore_failure: true
  - gsub:
      tag: gsub_dns_question_name_5c33b959
      field: dns.question.name
      pattern: "[.]$"
      replacement: ""
      ignore_failure: true
  - registered_domain:
      tag: registered_domain_dns_question_name_to_dns_question_c90ad4ff
      field: dns.question.name
      target_field: dns.question
  - remove:
      tag: remove_dns_question_domain_3403bb7d
      field: dns.question.domain
      ignore_missing: true
  - set:
      tag: set_gcp_dns_query_type_569889b2
      field: gcp.dns.query_type
      copy_from: json.jsonPayload.queryType
      ignore_failure: true
  - set:
      tag: set_dns_question_type_b79fcafb
      field: dns.question.type
      copy_from: gcp.dns.query_type
      ignore_failure: true
  - set:
      tag: set_gcp_dns_rdata_1320d1c1
      field: gcp.dns.rdata
      copy_from: json.jsonPayload.rdata
      ignore_failure: true
  ### Internal DNS query parsing
  - script:
      if: ctx.gcp?.dns?.rdata != null && ctx.gcp.dns.rdata != ""
      lang: painless
      tag: Process DNS RData
      description: This script processes the DNS RData into `dns.answers`.
      source: |
        def rdata = ctx.gcp.dns.rdata;
        def dns_answers = [];

        // Check for truncated answers.
        def truncated = rdata.endsWith("...") ? 1 : 0;

        // Process answers.
        def rdata_answers = /\n/.split(rdata);

        for (def i = 0; i < rdata_answers.length - truncated; i++) {
            def answer_parts = /\t/.split(rdata_answers[i]);

            // Assign answer parts.
            def name = answer_parts[0];
            def ttl = Long.parseLong(answer_parts[1]);
            def cls = answer_parts[2];
            def type = answer_parts[3];
            def data = answer_parts[4];

            // Remove trailing fullstop.
            if (name.endsWith(".")) {
                name = name.substring(0, name.length() - 1);
            }

            if (data.endsWith(".")) {
                data = data.substring(0, data.length() - 1);
            }

            // Uppercase type.
            type = type.toUpperCase();

            dns_answers.add([
                "name": name,
                "ttl": ttl,
                "class": cls,
                "type": type,
                "data": data
            ]);
        }
        ctx.dns.answers = dns_answers;
  ### External DNS query parsing
  - script:
      tag: script_223ceb8b
      lang: painless
      ignore_failure: true
      description: This script processes the Public DNS RData into `dns.answers`.
      if: ctx.json?.jsonPayload?.structuredRdata != null && ctx.json?.jsonPayload?.structuredRdata instanceof List
      source: >-
        List answers = new ArrayList();
        for (answer in ctx.json.jsonPayload.structuredRdata) {
          Map new_answer = new HashMap();
          if(answer.class != null) {
            new_answer.put("class", answer.class);
          }
          if(answer.type != null) {
            new_answer.put("type", answer.type);
          }
          if(answer.ttl != null) {
            new_answer.put("ttl", Long.parseLong(answer.ttl));
          }
          if(answer.rvalue != null) {
            new_answer.put("data", answer.rvalue);
            if (new_answer.data != null && new_answer.data.length() > 0 && new_answer.data.substring(new_answer.data.length() - 1) == '.') {
                new_answer.data = new_answer.data.substring(0, new_answer.data.length() - 1);
            }
            if (answer.domainName != null) {
              new_answer.put("name", answer.domainName);
            }
          }
          answers.add(new_answer);
        }
        if(ctx.dns.answers == null) {
            ctx.dns.put('answers',new ArrayList());
        }
        ctx.dns.answers = answers;
  - script:
      tag: script_81999a8f
      lang: painless
      ignore_failure: true
      if: ctx.dns?.answers != null && ctx.dns?.answers instanceof List
      source: >-
        List answers = new ArrayList();
        if(ctx.related == null) {
            ctx.put('related', new HashMap());
        }
        if(ctx.related.ip == null) {
            ctx.related.put('ip',new ArrayList());
        }
        if(ctx.dns.resolved_ip == null) {
            ctx.dns.put('resolved_ip',new ArrayList());
        }
        if(ctx.related.hosts == null) {
            ctx.related.put('hosts',new ArrayList());
        }
        for (answer in ctx.dns.answers) {
          if(['A','AAAA'].contains(answer.type)) {
            if(!ctx.related.ip.contains(answer.data)) {
                ctx.related.ip.add(answer.data);
            }
            if(!ctx.dns.resolved_ip.contains(answer.data)) {
                ctx.dns.resolved_ip.add(answer.data);
            }
          }
          if(['CNAME'].contains(answer.type) && !ctx.related.hosts.contains(answer.data)) {
            ctx.related.hosts.add(answer.data);
          }
          if(['MX'].contains(answer.type)) {
            def mx_server = / /.split(answer.data);
            if(mx_server[1] != null && !ctx.related.hosts.contains(mx_server[1]))
            ctx.related.hosts.add(mx_server[1]);
          }
        }
  - set:
      tag: set_gcp_dns_response_code_3c9fd546
      field: gcp.dns.response_code
      copy_from: json.jsonPayload.responseCode
      ignore_failure: true
  - set:
      tag: set_dns_response_code_e170bbe2
      field: dns.response_code
      copy_from: gcp.dns.response_code
      ignore_failure: true
  - set:
      tag: set_event_outcome_6c09e6cc
      field: event.outcome
      value: success
      if: ctx?.gcp?.dns?.response_code != null && ctx?.gcp?.dns?.response_code == "NOERROR"
  - set:
      tag: set_event_outcome_ce1e8037
      field: event.outcome
      value: failure
      if: ctx?.gcp?.dns?.response_code != null && ctx?.gcp?.dns?.response_code != "NOERROR"
  - set:
      tag: set_gcp_dns_server_latency_4141f4b0
      field: gcp.dns.server_latency
      copy_from: json.jsonPayload.serverLatency
      ignore_failure: true
  - set:
      tag: set_gcp_dns_source_ip_d2028402
      field: gcp.dns.source_ip
      copy_from: json.jsonPayload.sourceIP
      ignore_failure: true
  - set:
      tag: set_source_address_63abf5c7
      field: source.address
      copy_from: gcp.dns.source_ip
      ignore_failure: true
  - convert:
      tag: convert_gcp_dns_source_ip_to_source_ip_cfa9c148
      field: gcp.dns.source_ip
      target_field: source.ip
      type: ip
      ignore_failure: true
  - set:
      tag: set_gcp_dns_source_network_dc7a8a50
      field: gcp.dns.source_network
      copy_from: json.jsonPayload.sourceNetwork
      ignore_failure: true
  - set:
      tag: set_gcp_dns_vm_instance_id_b7c72bac
      field: gcp.dns.vm_instance_id
      copy_from: json.jsonPayload.vmInstanceIdString
      ignore_failure: true
  - set:
      tag: set_cloud_instance_id_c730509b
      field: cloud.instance.id
      copy_from: gcp.dns.vm_instance_id
      ignore_failure: true
  - set:
      tag: set_gcp_dns_vm_instance_name_9c9a44a5
      field: gcp.dns.vm_instance_name
      copy_from: json.jsonPayload.vmInstanceName
      ignore_failure: true
  - set:
      tag: set_cloud_instance_name_0eeff2a7
      field: cloud.instance.name
      copy_from: gcp.dns.vm_instance_name
      ignore_failure: true
  - gsub:
      tag: gsub_cloud_instance_name_1797899e
      field: cloud.instance.name
      pattern: "^.*[.]"
      replacement: ""
      ignore_failure: true
  - set:
      tag: set_gcp_dns_vm_project_id_dbb74a83
      field: gcp.dns.vm_project_id
      copy_from: json.jsonPayload.vmProjectId
      ignore_failure: true
  - set:
      tag: set_gcp_dns_vm_zone_name_8f171271
      field: gcp.dns.vm_zone_name
      copy_from: json.jsonPayload.vmZoneName
      ignore_failure: true
  - set:
      tag: set_cloud_availability_zone_e0244264
      field: cloud.availability_zone
      copy_from: gcp.dns.vm_zone_name
      ignore_failure: true
  - set:
      tag: set_gcp_dns_target_type_085129ae
      field: gcp.dns.target_type
      copy_from: json.resource.labels.target_type
      ignore_failure: true
  - set:
      tag: set_gcp_dns_source_type_2a595442
      field: gcp.dns.source_type
      copy_from: json.resource.labels.source_type
      ignore_failure: true
  - append:
      tag: append_related_ip_d7aecc5f
      field: related.ip
      value: "{{source.ip}}"
      allow_duplicates: false
      if: ctx.source?.ip != null
  - append:
      tag: append_related_ip_1164e6c1
      field: related.ip
      value: "{{destination.ip}}"
      allow_duplicates: false
      if: ctx.destination?.ip != null
  - append:
      tag: append_related_hosts_adfc73a4
      field: related.hosts
      value: "{{dns.question.name}}"
      allow_duplicates: false
      if: ctx.dns?.question?.name != null
  - rename:
      tag: rename_json_to_gcp_dns_flattened_8c4bcfef
      field: json
      target_field: gcp.dns.flattened
      if: ctx.json != null && ctx._conf?.keep_json == true
  - remove:
      tag: remove_00070c09
      field:
        - _conf
        - json
      ignore_missing: true
  - script:
      tag: script_4d6993cb
      lang: painless
      description: This script processor iterates over the whole document to remove fields with null values.
      source: |
        void handleMap(Map map) {
          for (def x : map.values()) {
            if (x instanceof Map) {
                handleMap(x);
            } else if (x instanceof List) {
                handleList(x);
            }
          }
          map.values().removeIf(v -> v == null || v == '' || (v instanceof Map && v.size() == 0) || (v instanceof List && v.size() == 0));
        }
        void handleList(List list) {
          for (def x : list) {
              if (x instanceof Map) {
                  handleMap(x);
              } else if (x instanceof List) {
                  handleList(x);
              }
          }
          list.removeIf(v -> v == null || v == '' || (v instanceof Map && v.size() == 0) || (v instanceof List && v.size() == 0));
        }
        handleMap(ctx);
on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: '{{{ _ingest.on_failure_message }}}'
  - append:
      field: tags
      value: preserve_original_event
      allow_duplicates: false
