---
description: Pipeline for processing BeyondInsight Workgroup Assets.
processors:
  - set:
      tag: set_ecs_version_c157feff
      field: ecs.version
      value: '9.1.0'
  - terminate:
      tag: data_collection_error
      if: ctx.error?.message != null && ctx.event?.original == null
      description: error message set and no data to process.
  - fingerprint:
      tag: fingerprint_b6cca44d
      description: >-
        This API does does not have a cursor.
        The integration collects all assets on each execution.
        The fingerprint prevents some duplication of assets that have not changed.
      fields:
        - event.original
      target_field: _id
  - json:
      field: event.original
      tag: json_event_original
      target_field: beyondinsight_password_safe.asset
  - script:
      tag: script_69fcb8e3
      description: Remove null values and empty strings from beyondinsight_password_safe.asset.
      lang: painless
      source: |
        ctx.beyondinsight_password_safe.asset.entrySet().removeIf(entry ->
          entry.getValue() == null ||
          (entry.getValue() instanceof String && entry.getValue().isEmpty())
        );
  - script:
      tag: script_numeric_id_to_string
      description: Convert numeric ID fields to strings.
      params:
        numeric_ids:
          - AssetID
          - WorkgroupID
      source: |
        for (field in params.numeric_ids) {
          def value = ctx.beyondinsight_password_safe.asset[field];
          if (value instanceof Number) {
            ctx.beyondinsight_password_safe.asset[field] =
              Integer.toString(value.intValue());
          }
        }
  - script:
      tag: script_camel_to_snake_naming
      description: Rename CapitalCamelCase-ish fields to lower_snake_case.
      params:
        field_mappings:
          AssetID: asset_id
          AssetName: asset_name
          AssetType: asset_type
          CreateDate: create_date
          DnsName: dns_name
          DomainName: domain_name
          IPAddress: ip_address
          LastUpdateDate: last_update_date
          MacAddress: mac_address
          OperatingSystem: operating_system
          WorkgroupID: workgroup_id
      source: |
        Map renamedFields = [:];
        for (entry in ctx.beyondinsight_password_safe.asset.entrySet()) {
          def originalKey = entry.getKey();
          def snakeKey = params.field_mappings[originalKey];
          if (snakeKey != null) {
            renamedFields[snakeKey] = entry.getValue();
          } else {
            renamedFields[originalKey] = entry.getValue();
          }
        }
        ctx.beyondinsight_password_safe.asset = renamedFields;
  - date:
      tag: date_beyondinsight_password_safe_asset_last_update_date_to_timestamp_18c49c68
      if: ctx.beyondinsight_password_safe?.asset?.last_update_date != null
      field: beyondinsight_password_safe.asset.last_update_date
      target_field: "@timestamp"
      formats:
        - ISO8601
  - set:
      tag: set_event_kind_18c57bf4
      field: event.kind
      value: asset
  - append:
      tag: append_event_category_3fa422a0
      field: event.category
      value: host
  - append:
      tag: append_event_type_8a66ccaa
      field: event.type
      value: info
  - set:
      tag: set_host_name_a33dce1f
      field: host.name
      copy_from: beyondinsight_password_safe.asset.asset_name
      ignore_empty_value: true
  - gsub:
      field: beyondinsight_password_safe.asset.mac_address
      ignore_missing: true
      pattern: '[:.]'
      replacement: '-'
      tag: gsub_mac_address
  - uppercase:
      tag: uppercase_beyondinsight_password_safe_asset_mac_address_6daad50f
      field: beyondinsight_password_safe.asset.mac_address
      ignore_missing: true
  - append:
      tag: append_host_mac_1d4125e8
      if: ctx.beyondinsight_password_safe?.asset?.mac_address != null
      field: host.mac
      value: '{{{beyondinsight_password_safe.asset.mac_address}}}'
  - set:
      tag: set_host_os_full_1bf9fb31
      if: ctx.beyondinsight_password_safe?.asset?.operating_system != null
      field: host.os.full
      copy_from: beyondinsight_password_safe.asset.operating_system
  - set:
      tag: set_host_domain_35027086
      if: ctx.beyondinsight_password_safe?.asset?.domain_name != null
      field: host.domain
      copy_from: beyondinsight_password_safe.asset.domain_name
  - gsub:
      tag: gsub_beyondinsight_password_safe_asset_ip_address_90b04f2c
      if: ctx.beyondinsight_password_safe?.asset?.ip_address != null
      description: Remove leading zeros from IP address octets.
      field: beyondinsight_password_safe.asset.ip_address
      pattern: "\\b0+(\\d)"
      replacement: "$1"
  - convert:
      tag: convert_beyondinsight_password_safe_asset_ip_address_235eb9d1
      if: ctx.beyondinsight_password_safe?.asset?.ip_address != null
      field: beyondinsight_password_safe.asset.ip_address
      type: ip
      on_failure:
        - remove:
            tag: remove_beyondinsight_password_safe_asset_ip_address_61920b7c
            field: beyondinsight_password_safe.asset.ip_address
  - append:
      tag: append_host_ip_0cebc425
      if: ctx.beyondinsight_password_safe?.asset?.ip_address != null
      field: host.ip
      value: "{{{beyondinsight_password_safe.asset.ip_address}}}"
      allow_duplicates: false
  - geoip:
      tag: geoip_host_ip_to_host_geo_b6f95445
      field: host.ip
      target_field: host.geo
      ignore_missing: true
      ignore_failure: true
  - append:
      tag: append_related_hosts_0d7db6fe
      if: ctx.beyondinsight_password_safe?.asset?.ip_address != null
      field: related.hosts
      value: '{{{beyondinsight_password_safe.asset.ip_address}}}'
      allow_duplicates: false
  - append:
      tag: append_related_hosts_3dd34fae
      if: ctx.beyondinsight_password_safe?.asset?.asset_name != null
      field: related.hosts
      value: '{{{beyondinsight_password_safe.asset.asset_name}}}'
      allow_duplicates: false
  - append:
      tag: append_related_hosts_cdb59436
      if: ctx.beyondinsight_password_safe?.asset?.dns_name != null
      field: related.hosts
      value: '{{{beyondinsight_password_safe.asset.dns_name}}}'
      allow_duplicates: false
  - append:
      tag: append_related_ip_8eff38ee
      if: ctx.beyondinsight_password_safe?.asset?.ip_address != null
      field: related.ip
      value: '{{{beyondinsight_password_safe.asset.ip_address}}}'
      allow_duplicates: false
on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: >-
        Processor '{{{ _ingest.on_failure_processor_type }}}'
        {{{#_ingest.on_failure_processor_tag}}}with tag '{{{ _ingest.on_failure_processor_tag }}}'
        {{{/_ingest.on_failure_processor_tag}}}failed with message '{{{ _ingest.on_failure_message }}}'
