#!/bin/bash

source .buildkite/scripts/common.sh

set -euo pipefail

unset_secrets
cleanup


if [[ "$BUILDKITE_PIPELINE_SLUG" == "integrations" ]]; then
    if [[ "$BUILDKITE_STEP_KEY" == "test-integrations-sync" ]]; then
       unset ELASTIC_PACKAGE_AWS_ACCESS_KEY
       unset ELASTIC_PACKAGE_AWS_SECRET_KEY
       unset AWS_ACCESS_KEY_ID
       unset AWS_SECRET_ACCESS_KEY
    fi
fi
