#!/bin/bash

source .buildkite/scripts/common.sh

set -euo pipefail

# Avoid any pager when running git commands
git config --global core.pager 'cat'

# default values used in different pipelines
export UPLOAD_SAFE_LOGS=${UPLOAD_SAFE_LOGS:-"0"}
export SERVERLESS=${SERVERLESS:-"false"}
export STACK_VERSION=${STACK_VERSION:-""}
export FORCE_CHECK_ALL=${FORCE_CHECK_ALL:-"false"}

BASE_DIR=$(pwd)
export BASE_DIR

GO_VERSION=$(cat .go-version)
export GO_VERSION

REPO_NAME=$(repo_name "${BUILDKITE_REPO}")
export REPO_NAME

export TMP_FOLDER_TEMPLATE_BASE="tmp.${REPO_NAME}"
export TMP_FOLDER_TEMPLATE="${TMP_FOLDER_TEMPLATE_BASE}.XXXXXXXXX"

REPO_BUILD_TAG="${REPO_NAME}/$(buildkite_pr_branch_build_id)"
export REPO_BUILD_TAG

JENKINS_API_TOKEN_PATH=kv/ci-shared/platform-ingest/jenkins_api_tokens
AWS_SERVICE_ACCOUNT_SECRET_PATH=kv/ci-shared/platform-ingest/aws_account_auth
SIGNING_PACKAGES_GCS_CREDENTIALS_PATH=kv/ci-shared/platform-ingest/signing_packages_gcs_artifacts_credentials
PACKAGE_UPLOADER_GCS_CREDENTIALS_PATH=kv/ci-shared/platform-ingest/package_storage_uploader
PRIVATE_CI_GCS_CREDENTIALS_PATH=kv/ci-shared/platform-ingest/private_ci_artifacts_gcs_credentials

BUILDKITE_API_TOKEN_PATH=kv/ci-shared/platform-ingest/buildkite_token

EC_TOKEN_PATH=kv/ci-shared/platform-ingest/platform-ingest-ec-qa
EC_DATA_PATH=secret/ci/elastic-integrations/ec_data

if [ -n "${ELASTIC_PACKAGE_LINKS_FILE_PATH+x}" ]; then
    # first upload pipeline does not have the environment variables defined in the YAML
    export ELASTIC_PACKAGE_LINKS_FILE_PATH=${BASE_DIR}/${ELASTIC_PACKAGE_LINKS_FILE_PATH}
fi

if [[ "${BUILDKITE_PIPELINE_SLUG}" == "integrations" ]]; then
    if [[ "${BUILDKITE_STEP_KEY}" == "publish-packages" ]]; then
        JENKINS_USERNAME_SECRET=$(retry 5 vault kv get -field username ${JENKINS_API_TOKEN_PATH})
        export JENKINS_USERNAME_SECRET
        JENKINS_HOST_SECRET=$(retry 5 vault kv get -field internal_ci_host ${JENKINS_API_TOKEN_PATH})
        export JENKINS_HOST_SECRET
        JENKINS_TOKEN=$(retry 5 vault kv get -field internal_ci ${JENKINS_API_TOKEN_PATH})
        export JENKINS_TOKEN

        # signing job
        SIGNING_PACKAGES_GCS_CREDENTIALS_SECRET=$(retry 5 vault kv get -field value ${SIGNING_PACKAGES_GCS_CREDENTIALS_PATH})
        export SIGNING_PACKAGES_GCS_CREDENTIALS_SECRET

        # publishing job
        PACKAGE_UPLOADER_GCS_CREDENTIALS_SECRET=$(retry 5 vault kv get -field value ${PACKAGE_UPLOADER_GCS_CREDENTIALS_PATH})
        export PACKAGE_UPLOADER_GCS_CREDENTIALS_SECRET
    fi
fi

if [[ "${BUILDKITE_PIPELINE_SLUG}" == "integrations" ]]; then
    if [[ "${BUILDKITE_STEP_KEY}" == "test-integrations" ]]; then
        BUILDKITE_API_TOKEN=$(retry 5 vault kv get -field buildkite_token ${BUILDKITE_API_TOKEN_PATH})
        export BUILDKITE_API_TOKEN
    fi

    if [[ "${BUILDKITE_STEP_KEY}" =~ ^test-integrations- ]]; then
        ELASTIC_PACKAGE_AWS_SECRET_KEY=$(retry 5 vault kv get -field secret_key ${AWS_SERVICE_ACCOUNT_SECRET_PATH})
        export ELASTIC_PACKAGE_AWS_SECRET_KEY
        ELASTIC_PACKAGE_AWS_ACCESS_KEY=$(retry 5 vault kv get -field access_key ${AWS_SERVICE_ACCOUNT_SECRET_PATH})
        export ELASTIC_PACKAGE_AWS_ACCESS_KEY

        PRIVATE_CI_GCS_CREDENTIALS_SECRET=$(retry 5 vault kv get -field plaintext ${PRIVATE_CI_GCS_CREDENTIALS_PATH})
        export PRIVATE_CI_GCS_CREDENTIALS_SECRET
        export JOB_GCS_BUCKET_INTERNAL="fleet-ci-temp-internal"

        # Environment variables required by the service deployer
        export AWS_SECRET_ACCESS_KEY=${ELASTIC_PACKAGE_AWS_SECRET_KEY}
        export AWS_ACCESS_KEY_ID=${ELASTIC_PACKAGE_AWS_ACCESS_KEY}

        BUILDKITE_API_TOKEN=$(retry 5 vault kv get -field buildkite_token ${BUILDKITE_API_TOKEN_PATH})
        export BUILDKITE_API_TOKEN
    fi
fi

if [[ "${BUILDKITE_PIPELINE_SLUG}" == "integrations-serverless" ]]; then
    if [[ "${BUILDKITE_STEP_KEY}" == "test-integrations-serverless-project" ]]; then
        ELASTIC_PACKAGE_AWS_SECRET_KEY=$(retry 5 vault kv get -field secret_key ${AWS_SERVICE_ACCOUNT_SECRET_PATH})
        export ELASTIC_PACKAGE_AWS_SECRET_KEY
        ELASTIC_PACKAGE_AWS_ACCESS_KEY=$(retry 5 vault kv get -field access_key ${AWS_SERVICE_ACCOUNT_SECRET_PATH})
        export ELASTIC_PACKAGE_AWS_ACCESS_KEY

        PRIVATE_CI_GCS_CREDENTIALS_SECRET=$(retry 5 vault kv get -field plaintext ${PRIVATE_CI_GCS_CREDENTIALS_PATH})
        export PRIVATE_CI_GCS_CREDENTIALS_SECRET
        export JOB_GCS_BUCKET_INTERNAL="fleet-ci-temp-internal"

        # Environment variables required by the service deployer
        export AWS_SECRET_ACCESS_KEY=${ELASTIC_PACKAGE_AWS_SECRET_KEY}
        export AWS_ACCESS_KEY_ID=${ELASTIC_PACKAGE_AWS_ACCESS_KEY}

        BUILDKITE_API_TOKEN=$(retry 5 vault kv get -field buildkite_token ${BUILDKITE_API_TOKEN_PATH})
        export BUILDKITE_API_TOKEN

        EC_API_KEY_SECRET=$(retry 5 vault kv get -field apiKey ${EC_TOKEN_PATH})
        export EC_API_KEY_SECRET
        EC_HOST_SECRET=$(retry 5 vault kv get -field url ${EC_TOKEN_PATH})
        export EC_HOST_SECRET
        EC_REGION_SECRET=$(retry 5 vault read -field region_qa ${EC_DATA_PATH})
        export EC_REGION_SECRET
    fi
fi
