#!/bin/bash

source .buildkite/scripts/common.sh

set -euo pipefail

export BASE_DIR=$(pwd)
export GO_VERSION=$(cat .go-version)
export startTimeInMillis="$(date +%s%3N)"
export ELASTIC_PACKAGE_LINKS_FILE_PATH=${BASE_DIR}/${ELASTIC_PACKAGE_LINKS_FILE_PATH}
