---
description: Pipeline for processing nod feed
processors:
  - set:
      tag: set_ecs_version_f5923549
      field: ecs.version
      value: '8.17.0'

  - terminate:
      tag: data_collection_error
      if: ctx.error?.message != null
      description: error message set and no data to process.

  - rename:
      tag: rename_message_to_event_original_56a77271
      field: message
      target_field: event.original
      ignore_missing: true
      if: ctx.event?.original == null

  - remove:
      field: message
      tag: remove_message
      ignore_missing: true
      description: The `message` field is no longer required if the document has an `event.original` field.
      if: ctx.event?.original != null

  - json:
      tag: json_event_original_to_domaintools_4eea6ad1
      field: event.original
      target_field: domaintools

    ############################
    # Generic indicator fields #
    ############################
  - set:
      tag: set_threat_indicator_type_b65d5b6f
      field: threat.indicator.type
      value: domain-name
  - set:
      tag: set_threat_indicator_name_1bc8d54d
      if: ctx.domaintools?.domain != null
      field: threat.indicator.name
      copy_from: domaintools.domain

    ####################
    # Event ECS fields #
    ####################
  - set:
      tag: set_event_kind_a131107f
      field: event.kind
      value: enrichment
  - set:
      tag: set_event_category_cceb7c22
      field: event.category
      value: ['threat']
  - set:
      tag: set_event_type_97bb78b9
      field: event.type
      value: ['indicator']

on_failure:
- set:
      field: event.kind
      value: pipeline_error
- append:
    field: tags
    value: preserve_original_event
    allow_duplicates: false
- append:
      field: error.message
      value: >-
        Processor '{{{ _ingest.on_failure_processor_type }}}'
        {{{#_ingest.on_failure_processor_tag}}}with tag '{{{ _ingest.on_failure_processor_tag }}}'
        {{{/_ingest.on_failure_processor_tag}}}failed with message '{{{ _ingest.on_failure_message }}}'
