---
description: Pipeline for parsing GCP PubSub metrics.
processors:
  - fingerprint:
      tag: fingerprint_to_gcp_labels_fingerprint_5c1d1252
      fields:
        - gcp.labels
      target_field: gcp.labels_fingerprint
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_snapshot_backlog_bytes_to_gcp_pubsub_snapshot_backlog_bytes_33c8f8dc
      field: gcp.metrics.snapshot.backlog.bytes
      target_field: gcp.pubsub.snapshot.backlog.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_snapshot_backlog_bytes_by_region_bytes_to_gcp_pubsub_snapshot_backlog_bytes_by_region_bytes_1b0b7336
      field: gcp.metrics.snapshot.backlog_bytes_by_region.bytes
      target_field: gcp.pubsub.snapshot.backlog_bytes_by_region.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_snapshot_config_updates_count_to_gcp_pubsub_snapshot_config_updates_count_0890b5f4
      field: gcp.metrics.snapshot.config_updates.count
      target_field: gcp.pubsub.snapshot.config_updates.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_snapshot_num_messages_value_to_gcp_pubsub_snapshot_num_messages_value_88cffd7c
      field: gcp.metrics.snapshot.num_messages.value
      target_field: gcp.pubsub.snapshot.num_messages.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_snapshot_num_messages_by_region_value_to_gcp_pubsub_snapshot_num_messages_by_region_value_d114ab98
      field: gcp.metrics.snapshot.num_messages_by_region.value
      target_field: gcp.pubsub.snapshot.num_messages_by_region.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_snapshot_oldest_message_age_sec_to_gcp_pubsub_snapshot_oldest_message_age_sec_f4d08bdc
      field: gcp.metrics.snapshot.oldest_message_age.sec
      target_field: gcp.pubsub.snapshot.oldest_message_age.sec
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_snapshot_oldest_message_age_by_region_sec_to_gcp_pubsub_snapshot_oldest_message_age_by_region_sec_38d8da1c
      field: gcp.metrics.snapshot.oldest_message_age_by_region.sec
      target_field: gcp.pubsub.snapshot.oldest_message_age_by_region.sec
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_ack_message_count_to_gcp_pubsub_subscription_ack_message_count_d684afea
      field: gcp.metrics.subscription.ack_message.count
      target_field: gcp.pubsub.subscription.ack_message.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_backlog_bytes_to_gcp_pubsub_subscription_backlog_bytes_719d08ba
      field: gcp.metrics.subscription.backlog.bytes
      target_field: gcp.pubsub.subscription.backlog.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_byte_cost_bytes_to_gcp_pubsub_subscription_byte_cost_bytes_4771ca74
      field: gcp.metrics.subscription.byte_cost.bytes
      target_field: gcp.pubsub.subscription.byte_cost.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_config_updates_count_to_gcp_pubsub_subscription_config_updates_count_f573b6cc
      field: gcp.metrics.subscription.config_updates.count
      target_field: gcp.pubsub.subscription.config_updates.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_dead_letter_message_count_to_gcp_pubsub_subscription_dead_letter_message_count_7f96993e
      field: gcp.metrics.subscription.dead_letter_message.count
      target_field: gcp.pubsub.subscription.dead_letter_message.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_mod_ack_deadline_message_count_to_gcp_pubsub_subscription_mod_ack_deadline_message_count_ff3a4b20
      field: gcp.metrics.subscription.mod_ack_deadline_message.count
      target_field: gcp.pubsub.subscription.mod_ack_deadline_message.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_mod_ack_deadline_message_operation_count_to_gcp_pubsub_subscription_mod_ack_deadline_message_operation_count_de135a18
      field: gcp.metrics.subscription.mod_ack_deadline_message_operation.count
      target_field: gcp.pubsub.subscription.mod_ack_deadline_message_operation.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_mod_ack_deadline_request_count_to_gcp_pubsub_subscription_mod_ack_deadline_request_count_a744b268
      field: gcp.metrics.subscription.mod_ack_deadline_request.count
      target_field: gcp.pubsub.subscription.mod_ack_deadline_request.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_num_outstanding_messages_value_to_gcp_pubsub_subscription_num_outstanding_messages_value_d30c43f4
      field: gcp.metrics.subscription.num_outstanding_messages.value
      target_field: gcp.pubsub.subscription.num_outstanding_messages.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_num_undelivered_messages_value_to_gcp_pubsub_subscription_num_undelivered_messages_value_5466ef70
      field: gcp.metrics.subscription.num_undelivered_messages.value
      target_field: gcp.pubsub.subscription.num_undelivered_messages.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_oldest_retained_acked_message_age_sec_to_gcp_pubsub_subscription_oldest_retained_acked_message_age_sec_35cf7b52
      field: gcp.metrics.subscription.oldest_retained_acked_message_age.sec
      target_field: gcp.pubsub.subscription.oldest_retained_acked_message_age.sec
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_oldest_retained_acked_message_age_by_region_value_to_gcp_pubsub_subscription_oldest_retained_acked_message_age_by_region_value_20e2c834
      field: gcp.metrics.subscription.oldest_retained_acked_message_age_by_region.value
      target_field: gcp.pubsub.subscription.oldest_retained_acked_message_age_by_region.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_oldest_unacked_message_age_sec_to_gcp_pubsub_subscription_oldest_unacked_message_age_sec_d82694a0
      field: gcp.metrics.subscription.oldest_unacked_message_age.sec
      target_field: gcp.pubsub.subscription.oldest_unacked_message_age.sec
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_oldest_unacked_message_age_by_region_value_to_gcp_pubsub_subscription_oldest_unacked_message_age_by_region_value_f1029308
      field: gcp.metrics.subscription.oldest_unacked_message_age_by_region.value
      target_field: gcp.pubsub.subscription.oldest_unacked_message_age_by_region.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_pull_ack_message_operation_count_to_gcp_pubsub_subscription_pull_ack_message_operation_count_4d15e94c
      field: gcp.metrics.subscription.pull_ack_message_operation.count
      target_field: gcp.pubsub.subscription.pull_ack_message_operation.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_pull_ack_request_count_to_gcp_pubsub_subscription_pull_ack_request_count_8cdde46c
      field: gcp.metrics.subscription.pull_ack_request.count
      target_field: gcp.pubsub.subscription.pull_ack_request.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_pull_message_operation_count_to_gcp_pubsub_subscription_pull_message_operation_count_ecbf71e0
      field: gcp.metrics.subscription.pull_message_operation.count
      target_field: gcp.pubsub.subscription.pull_message_operation.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_pull_request_count_to_gcp_pubsub_subscription_pull_request_count_721d0c10
      field: gcp.metrics.subscription.pull_request.count
      target_field: gcp.pubsub.subscription.pull_request.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_push_request_count_to_gcp_pubsub_subscription_push_request_count_27570fac
      field: gcp.metrics.subscription.push_request.count
      target_field: gcp.pubsub.subscription.push_request.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_retained_acked_bytes_to_gcp_pubsub_subscription_retained_acked_bytes_b7315c90
      field: gcp.metrics.subscription.retained_acked.bytes
      target_field: gcp.pubsub.subscription.retained_acked.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_retained_acked_bytes_by_region_bytes_to_gcp_pubsub_subscription_retained_acked_bytes_by_region_bytes_95db0014
      field: gcp.metrics.subscription.retained_acked_bytes_by_region.bytes
      target_field: gcp.pubsub.subscription.retained_acked_bytes_by_region.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_seek_request_count_to_gcp_pubsub_subscription_seek_request_count_4992ba08
      field: gcp.metrics.subscription.seek_request.count
      target_field: gcp.pubsub.subscription.seek_request.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_sent_message_count_to_gcp_pubsub_subscription_sent_message_count_8852cf64
      field: gcp.metrics.subscription.sent_message.count
      target_field: gcp.pubsub.subscription.sent_message.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_streaming_pull_ack_message_operation_count_to_gcp_pubsub_subscription_streaming_pull_ack_message_operation_count_7a86a350
      field: gcp.metrics.subscription.streaming_pull_ack_message_operation.count
      target_field: gcp.pubsub.subscription.streaming_pull_ack_message_operation.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_streaming_pull_ack_request_count_to_gcp_pubsub_subscription_streaming_pull_ack_request_count_0c7daef8
      field: gcp.metrics.subscription.streaming_pull_ack_request.count
      target_field: gcp.pubsub.subscription.streaming_pull_ack_request.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_streaming_pull_message_operation_count_to_gcp_pubsub_subscription_streaming_pull_message_operation_count_8c290604
      field: gcp.metrics.subscription.streaming_pull_message_operation.count
      target_field: gcp.pubsub.subscription.streaming_pull_message_operation.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_streaming_pull_mod_ack_deadline_message_operation_count_to_gcp_pubsub_subscription_streaming_pull_mod_ack_deadline_message_operation_count_4678a3f4
      field: gcp.metrics.subscription.streaming_pull_mod_ack_deadline_message_operation.count
      target_field: gcp.pubsub.subscription.streaming_pull_mod_ack_deadline_message_operation.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_streaming_pull_mod_ack_deadline_request_count_to_gcp_pubsub_subscription_streaming_pull_mod_ack_deadline_request_count_09e2de14
      field: gcp.metrics.subscription.streaming_pull_mod_ack_deadline_request.count
      target_field: gcp.pubsub.subscription.streaming_pull_mod_ack_deadline_request.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_streaming_pull_response_count_to_gcp_pubsub_subscription_streaming_pull_response_count_90934e74
      field: gcp.metrics.subscription.streaming_pull_response.count
      target_field: gcp.pubsub.subscription.streaming_pull_response.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_unacked_bytes_by_region_bytes_to_gcp_pubsub_subscription_unacked_bytes_by_region_bytes_adc53c30
      field: gcp.metrics.subscription.unacked_bytes_by_region.bytes
      target_field: gcp.pubsub.subscription.unacked_bytes_by_region.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_topic_byte_cost_bytes_to_gcp_pubsub_topic_byte_cost_bytes_62b96d20
      field: gcp.metrics.topic.byte_cost.bytes
      target_field: gcp.pubsub.topic.byte_cost.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_topic_config_updates_count_to_gcp_pubsub_topic_config_updates_count_053b35fe
      field: gcp.metrics.topic.config_updates.count
      target_field: gcp.pubsub.topic.config_updates.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_topic_message_sizes_bytes_to_gcp_pubsub_topic_message_sizes_bytes_a285e4d8
      field: gcp.metrics.topic.message_sizes.bytes
      target_field: gcp.pubsub.topic.message_sizes.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_topic_oldest_retained_acked_message_age_by_region_value_to_gcp_pubsub_topic_oldest_retained_acked_message_age_by_region_value_0df2e754
      field: gcp.metrics.topic.oldest_retained_acked_message_age_by_region.value
      target_field: gcp.pubsub.topic.oldest_retained_acked_message_age_by_region.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_topic_oldest_unacked_message_age_by_region_value_to_gcp_pubsub_topic_oldest_unacked_message_age_by_region_value_6fd7e0f4
      field: gcp.metrics.topic.oldest_unacked_message_age_by_region.value
      target_field: gcp.pubsub.topic.oldest_unacked_message_age_by_region.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_topic_retained_acked_bytes_by_region_bytes_to_gcp_pubsub_topic_retained_acked_bytes_by_region_bytes_bd104444
      field: gcp.metrics.topic.retained_acked_bytes_by_region.bytes
      target_field: gcp.pubsub.topic.retained_acked_bytes_by_region.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_topic_send_message_operation_count_to_gcp_pubsub_topic_send_message_operation_count_5a30e320
      field: gcp.metrics.topic.send_message_operation.count
      target_field: gcp.pubsub.topic.send_message_operation.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_topic_send_request_count_to_gcp_pubsub_topic_send_request_count_3746a888
      field: gcp.metrics.topic.send_request.count
      target_field: gcp.pubsub.topic.send_request.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_topic_streaming_pull_response_count_to_gcp_pubsub_topic_streaming_pull_response_count_cc035cd4
      field: gcp.metrics.topic.streaming_pull_response.count
      target_field: gcp.pubsub.topic.streaming_pull_response.count
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_topic_unacked_bytes_by_region_bytes_to_gcp_pubsub_topic_unacked_bytes_by_region_bytes_85ceca3c
      field: gcp.metrics.topic.unacked_bytes_by_region.bytes
      target_field: gcp.pubsub.topic.unacked_bytes_by_region.bytes
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_ack_latencies_value_to_gcp_pubsub_subscription_ack_latencies_value_ab1fdd24
      field: gcp.metrics.subscription.ack_latencies.value
      target_field: gcp.pubsub.subscription.ack_latencies.value
      ignore_missing: true
  - rename:
      tag: rename_gcp_metrics_subscription_push_request_latencies_value_to_gcp_pubsub_subscription_push_request_latencies_value_691c1cac
      field: gcp.metrics.subscription.push_request_latencies.value
      target_field: gcp.pubsub.subscription.push_request_latencies.value
      ignore_missing: true
  - remove:
      tag: remove_ab6e04c7
      field:
        - gcp.metrics
      ignore_missing: true
on_failure:
  - set:
      tag: set_event_kind_72b1902f
      field: event.kind
      value: pipeline_error
  - append:
      tag: append_error_message_206bb8ac
      field: error.message
      value: >-
        Processor '{{{ _ingest.on_failure_processor_type }}}'
        {{{#_ingest.on_failure_processor_tag}}}with tag '{{{ _ingest.on_failure_processor_tag }}}'
        {{{/_ingest.on_failure_processor_tag}}}failed with message '{{{ _ingest.on_failure_message }}}'
  - append:
      tag: append_tags_279d5a5c
      field: tags
      value: preserve_original_event
      allow_duplicates: false
