fields:
  - name: timestamp
    period: -24h
  - name: colo_code
    enum: [MRS, SFO, JFK, LAX, LHR, FRA, NRT, SIN, SYD, GRU]
  - name: edns_subnet
    cardinality: 5000
  - name: edns_subnet_length
    range:
      min: 0
      max: 32
  - name: query_name
    cardinality: 50000
  - name: query_type
    enum: [1, 2, 5, 6, 12, 15, 16, 28, 33]
  - name: response_cached
    enum: ["true", "false"]
  - name: response_code
    enum: [0, 1, 2, 3, 4, 5]
  - name: source_ip
    cardinality: 10000
