from __future__ import print_function

import io
import os
import unittest


class ReadmeTest(unittest.TestCase):
    def setUp(self):
        # type: () -> None
        self.package_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        self.readme_path = os.path.join(self.package_dir, 'docs', 'README.md')
        self.readme_template_path = os.path.join(
            self.package_dir,
            '_dev',
            'build',
            'docs',
            'README.md',
        )

    def test_readme_has_no_template_placeholders(self):
        # type: () -> None
        with io.open(self.readme_path, 'r', encoding='utf-8') as handle:
            content = handle.read()

        disallowed_markers = [
            '{Data stream name}',
            '{data stream name}',
            '{source}',
            '{list types}',
            'Vendor documentation link 1',
            'Vendor documentation link 2',
            'Vendor documentation link 3',
            'These APIs are used with this integration:\n* ...',
            'replace the placeholder package `sample_event.json`',
        ]

        for marker in disallowed_markers:
            self.assertNotIn(marker, content)

    def test_readme_uses_namespace_safe_transform_source(self):
        # type: () -> None
        with io.open(self.readme_path, 'r', encoding='utf-8') as handle:
            content = handle.read()

        self.assertIn('logs-tychon_quantum_command.tychon_pqc-*', content)
        self.assertIn('logs-tychon_quantum_command.tychon_pqc-<namespace>', content)
        self.assertIn('`logs-tychon_quantum_command.tychon_pqc`', content)
        self.assertIn('.ds-logs-tychon_quantum_command.tychon_pqc-<namespace>-YYYY.MM.DD-000001', content)
        self.assertNotIn('logs-tychon_pqc-*', content)

    def test_readme_template_exists_and_uses_generated_header(self):
        # type: () -> None
        self.assertTrue(os.path.isfile(self.readme_template_path))

        with io.open(self.readme_template_path, 'r', encoding='utf-8') as handle:
            content = handle.read()

        self.assertTrue(content.startswith('{{ generatedHeader }}\n\n'))
        self.assertNotIn('<!-- NOTICE: Do not edit this file manually.-->\n', content)
        self.assertNotIn('replace the placeholder package `sample_event.json`', content)


if __name__ == '__main__':
    unittest.main()
