# newer versions go on top
- version: "0.1.1"
  changes:
    - description: Update package title and description to improve clarity of use.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/19526
- version: "0.1.0"
  changes:
    - description: Initial release of the Prometheus OpenTelemetry Input package with guided configuration
      type: enhancement
      link: https://github.com/elastic/integrations/pull/17117
