// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

package changelog

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/cli/go-gh/v2"

	"github.com/elastic/integrations/cmd/backport/gitutil"
)

// SyncResult holds outputs produced by CreateSyncPR.
type SyncResult struct {
	// NotFoundPackages lists package names that could not be resolved on main.
	NotFoundPackages []string
	// Outcome is "success", "skipped", or "error".
	Outcome string
}

// CreateSyncPR applies the changelog entries from entriesTSV onto main,
// commits them to workingBranch, and opens a GitHub PR.
// workDir is the repository root; an empty string uses the current working directory.
func CreateSyncPR(workDir, entriesTSV, workingBranch, backportPRNumber, backportBranch, packagesDir, repository string) (*SyncResult, error) {
	git := gitutil.Git{Dir: workDir}

	if !filepath.IsAbs(packagesDir) {
		packagesDir = filepath.Join(workDir, packagesDir)
	}

	if err := git.RunToStderr("checkout", "-b", workingBranch, "origin/main"); err != nil {
		return nil, fmt.Errorf("creating working branch: %w", err)
	}

	entries, err := readEntriesTSV(entriesTSV)
	if err != nil {
		return nil, fmt.Errorf("reading entries TSV: %w", err)
	}

	pkgIndex, err := BuildPackageIndex(packagesDir)
	if err != nil {
		return nil, fmt.Errorf("building package index: %w", err)
	}

	var notFound []string
	var applied []tsvEntry

	for _, e := range entries {
		pkgDir, ok := pkgIndex[e.pkg]
		if !ok {
			notFound = append(notFound, e.pkg)
			continue
		}

		changelogPath := filepath.Join(pkgDir, "changelog.yml")
		entryBlock, err := os.ReadFile(e.entryFile)
		if err != nil {
			return nil, fmt.Errorf("reading entry file %s: %w", e.entryFile, err)
		}
		_ = os.Remove(e.entryFile)
		if err := InsertEntry(changelogPath, e.version, strings.TrimRight(string(entryBlock), "\n")); err != nil {
			return nil, fmt.Errorf("inserting entry for %s: %w", e.pkg, err)
		}
		if err := git.RunToStderr("add", changelogPath); err != nil {
			return nil, err
		}
		applied = append(applied, e)
	}

	if len(applied) == 0 {
		_ = git.RunToStderr("checkout", backportBranch)
		return &SyncResult{NotFoundPackages: notFound, Outcome: "skipped"}, nil
	}

	commitMsg := buildCommitMessage(applied, backportPRNumber)
	prTitle := buildPRTitle(applied, backportPRNumber)

	if err := git.RunToStderr("commit", "-m", commitMsg); err != nil {
		return nil, fmt.Errorf("committing: %w", err)
	}
	// A previous failed run may have left this branch on the remote. Refresh the
	// remote-tracking ref so --force-with-lease has something to compare against,
	// then overwrite it — the branch is machine-owned and named after the PR.
	_ = git.RunToStderr("fetch", "origin",
		fmt.Sprintf("refs/heads/%s:refs/remotes/origin/%s", workingBranch, workingBranch))
	if err := git.RunToStderr("push", "--force-with-lease", "origin", workingBranch); err != nil {
		return nil, fmt.Errorf("pushing: %w", err)
	}

	body := fmt.Sprintf("Automated changelog sync from backport PR #%s.\n\nGenerated by the sync-backport-changelog workflow.", backportPRNumber)

	prArgs := []string{
		"pr", "create",
		"--base", "main",
		"--head", workingBranch,
		"--title", prTitle,
		"--label", "backport:sync-changelog",
		"--label", "changelog-link-check:skip",
		"--reviewer", "elastic/ecosystem",
		"--body", body,
	}
	if assignee := resolveAssignee(backportPRNumber, repository); assignee != "" {
		prArgs = append(prArgs, "--assignee", assignee)
	}
	_, _, err = gh.Exec(prArgs...)
	if err != nil {
		return nil, fmt.Errorf("creating PR: %w", err)
	}

	_ = git.RunToStderr("checkout", backportBranch)
	return &SyncResult{NotFoundPackages: notFound, Outcome: "success"}, nil
}

type prActor struct {
	Login string `json:"login"`
	IsBot bool   `json:"is_bot"`
}

// resolveAssignee returns the login that should be set as assignee on the sync
// PR. It prefers the backport PR author when they are not a bot and have repo
// write access, and falls back to whoever merged the PR when they are not a
// bot. Returns an empty string on any lookup failure so the caller can skip
// the --assignee flag gracefully.
func resolveAssignee(prNumber, repository string) string {
	stdout, _, err := gh.Exec("pr", "view", prNumber, "--repo", repository,
		"--json", "author,mergedBy")
	if err != nil {
		return ""
	}
	var data struct {
		Author   prActor `json:"author"`
		MergedBy prActor `json:"mergedBy"`
	}
	if err := json.Unmarshal(stdout.Bytes(), &data); err != nil {
		return ""
	}
	hasWriteAccess := func(login string) bool {
		out, _, err := gh.Exec("api",
			fmt.Sprintf("repos/%s/collaborators/%s/permission", repository, login),
			"--jq", ".permission")
		if err != nil {
			return false
		}
		perm := strings.TrimSpace(out.String())
		return perm == "write" || perm == "maintain" || perm == "admin"
	}
	return pickAssignee(data.Author, data.MergedBy, hasWriteAccess)
}

// pickAssignee returns the author login when the author is not a bot and has
// repo write access. Falls back to mergedBy when the author check fails, as
// long as mergedBy is not a bot. Returns empty string if neither qualifies.
func pickAssignee(author, mergedBy prActor, hasWriteAccess func(string) bool) string {
	if !author.IsBot && author.Login != "" && hasWriteAccess(author.Login) {
		return author.Login
	}
	if !mergedBy.IsBot && mergedBy.Login != "" {
		return mergedBy.Login
	}
	return ""
}

type tsvEntry struct{ pkg, version, entryFile string }

func readEntriesTSV(path string) ([]tsvEntry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var entries []tsvEntry
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		parts := strings.SplitN(sc.Text(), "\t", 3)
		if len(parts) != 3 {
			continue
		}
		entries = append(entries, tsvEntry{pkg: parts[0], version: parts[1], entryFile: parts[2]})
	}
	return entries, sc.Err()
}

func buildCommitMessage(entries []tsvEntry, prNumber string) string {
	if len(entries) == 1 {
		return fmt.Sprintf("changelog: %s %s (backport sync from PR #%s)", entries[0].pkg, entries[0].version, prNumber)
	}
	return fmt.Sprintf("changelog: backport sync from PR #%s", prNumber)
}

func buildPRTitle(entries []tsvEntry, prNumber string) string {
	return buildCommitMessage(entries, prNumber)
}
