FROM docker.elastic.co/package-registry/package-registry:51947a80a0b45e0cd8e0f4c241e4886a89eacd68

COPY testing/environments/package-registry.config.yml /package-registry/config.yml
COPY build/integrations /packages/integrations