# Mock for cluster version only: GET /api/v1/config/clusterversion → 1 JSON body → 1 event per collection.
rules:
  - path: /api/v1/config/clusterversion
    methods: [GET]
    request_headers:
      Authorization:
        - Api-Token testtoken
    responses:
      - status_code: 200
        body: |-
          {{ minify_json `
          {"version":"1.247.0.20220707-181710"}
          `}}
