fields:
  - name: session_start_time
    period: -24h
  - name: session_end_time
    period: -24h
  - name: account_id
    cardinality: 100
  - name: bytes_received
    range:
      min: 0
      max: 100000
  - name: bytes_sent
    range:
      min: 0
      max: 100000
  - name: client_tcp_handshake_duration_ms
    range:
      min: 0
      max: 500
  - name: client_tls_cipher
    enum: [TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256]
  - name: client_tls_handshake_duration_ms
    range:
      min: 0
      max: 1000
  - name: client_tls_version
    enum: ["none", "TLS 1.2", "TLS 1.3"]
  - name: connection_close_reason
    enum: [CLIENT_CLOSED, CLIENT_TLS_ERROR, SERVER_CLOSED, TIMEOUT, ERROR, UNKNOWN]
  - name: destination_tunnel_id
    cardinality: 100
  - name: device_id
    cardinality: 10000
  - name: device_name
    cardinality: 10000
  - name: egress_colo_name
    cardinality: 200
  - name: egress_ip
    cardinality: 5000
  - name: egress_port
    range:
      min: 1024
      max: 65535
  - name: egress_rule_id
    cardinality: 100
  - name: egress_rule_name
    cardinality: 100
  - name: email
    cardinality: 5000
  - name: ingress_colo_name
    cardinality: 200
  - name: offramp
    enum: [INTERNET, PRIVATE, WARP]
  - name: origin_ip
    cardinality: 5000
  - name: origin_port
    range:
      min: 1
      max: 65535
  - name: origin_tls_certificate_issuer
    cardinality: 100
  - name: origin_tls_certificate_validation_result
    enum: [VALID, INVALID, EXPIRED, UNKNOWN]
  - name: origin_tls_cipher
    enum: [TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]
  - name: origin_tls_handshake_duration_ms
    range:
      min: 0
      max: 1000
  - name: origin_tls_version
    enum: ["TLS 1.2", "TLS 1.3"]
  - name: protocol
    enum: [TCP, UDP]
  - name: rule_evaluation_duration_ms
    range:
      min: 0
      max: 100
  - name: session_id
    cardinality: 100000
  - name: source_internal_ip
    cardinality: 5000
  - name: source_ip
    cardinality: 10000
  - name: source_port
    range:
      min: 1024
      max: 65535
  - name: user_id
    cardinality: 5000
  - name: virtual_network_id
    cardinality: 100
