version: "2.3"
services:
  ti-polyswarm-scans:
    image: docker.elastic.co/observability/stream:v0.23.0
    hostname: ti-polyswarm-scans
    ports:
      - 8080
    volumes:
      - ./files:/files:ro
    command:
      - http-server
      - --addr=:8080
      - --config=/files/config-scans.yml
