fields:
  - name: timestamp
    period: -24h
  - name: action_result
    enum:
      - "true"
      - "false"
  - name: action_type
    enum:
      - token_create
      - token_delete
      - token_update
      - login
      - logout
      - user_update
      - zone_create
      - zone_delete
      - dns_record_create
      - dns_record_update
  - name: actor_email
    cardinality: 1000
  - name: actor_id
    cardinality: 1000
  - name: actor_ip
    cardinality: 5000
  - name: actor_type
    enum:
      - user
      - admin
      - system
  - name: id
    cardinality: 100000
  - name: interface
    enum:
      - UI
      - API
  - name: owner_id
    cardinality: 1000
  - name: resource_id
    cardinality: 5000
  - name: resource_type
    enum:
      - account
      - zone
      - dns_record
      - token
      - user
      - page_rule
