fields:
  - name: timestamp
    period: -24h
  - name: connect_timestamp
    period: -24h
  - name: disconnect_timestamp
    period: -24h
  - name: application
    cardinality: 1000
  - name: client_asn
    range:
      min: 1
      max: 400000
  - name: client_bytes
    range:
      min: 0
      max: 100000
  - name: client_country
    cardinality: 200
  - name: client_ip
    cardinality: 10000
  - name: client_matched_ip_firewall
    enum: [UNKNOWN, ALLOW, BLOCK, CHALLENGE, WHITELIST, BYPASS, JS_CHALLENGE]
  - name: client_port
    range:
      min: 1024
      max: 65535
  - name: client_proto
    enum: [tcp, udp]
  - name: client_tcp_rtt
    range:
      min: 0
      max: 1000
  - name: client_tls_cipher
    enum: [UNK, AEAD-AES128-GCM-SHA256, AEAD-AES256-GCM-SHA384, AEAD-CHACHA20-POLY1305-SHA256]
  - name: client_tls_client_hello_server_name
    cardinality: 5000
  - name: client_tls_protocol
    enum: [unknown, none, TLSv1, TLSv1.1, TLSv1.2, TLSv1.3]
  - name: client_tls_status
    enum: [UNKNOWN, OK, INTERNAL_ERROR, INVALID_CONFIG, INVALID_SNI, HANDSHAKE_FAILED]
  - name: colo_code
    cardinality: 200
  - name: event
    enum: [connect, disconnect, clientHello, tlsError, originError, originConnect]
  - name: origin_bytes
    range:
      min: 0
      max: 100000
  - name: origin_ip
    cardinality: 5000
  - name: origin_port
    range:
      min: 1
      max: 65535
  - name: origin_proto
    enum: [tcp, udp]
  - name: origin_tcp_rtt
    range:
      min: 0
      max: 1000
  - name: origin_tls_cipher
    enum: [UNK, AEAD-AES128-GCM-SHA256, AEAD-AES256-GCM-SHA384]
  - name: origin_tls_fingerprint
    cardinality: 1000
  - name: origin_tls_mode
    enum: [off, flexible, full, strict]
  - name: origin_tls_protocol
    enum: [unknown, none, TLSv1, TLSv1.1, TLSv1.2, TLSv1.3]
  - name: origin_tls_status
    enum: [UNKNOWN, OK, INTERNAL_ERROR, INVALID_CONFIG, INVALID_SNI, HANDSHAKE_FAILED]
  - name: proxy_protocol
    enum: [off, v1, v2, simple]
  - name: status
    value: 0
